### ISSUE TITLE
BNetzA-MaStR-API

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#10]
WSDL-API

* [SoapUI](https://de.wikipedia.org/wiki/SoapUI)
* [Python with Zeep](https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/postprocessing/BNetzA_MaStR_API.ipynb)

**Comment by Ludee** [comment]
I still can't find the _apiKey_. Is it the _Supportcode_ from _Stammdaten_?

**Comment by nesnoj** [comment]
But you do not need an authentication as you simply pass your apiKey (and your MaStR no. if needed) to the desired function. So I don't think this is the problem. As stated above, I was able to get my Tageskontingent which requires a successful authentication.

**Comment by nesnoj** [comment]
Good to know.
There's a good list of alternatives on [SE](https://stackoverflow.com/questions/206154/what-soap-client-libraries-exist-for-python-and-where-is-the-documentation-for). It may be worth to try `suds-py3`..

I tried SoapUI, time with auth worked but not the interesting functions - when adding a request that requires authentication I always get
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <s:Fault>
         <faultcode>s:Receiver.ZugriffVerweigert</faultcode>
         <faultstring xml:lang="de-DE">apiKey fehlt</faultstring>
      </s:Fault>
   </s:Body>
</s:Envelope>
```
But the apiKey was supplied.. o_O

Were you able to scrape them using `GetListeAlleEinheiten()` ? How did you do it?

**Comment by christian-rli** [comment]
When creating:

`client = Client(wsdl=wsdl, transport=transport, settings=settings)`

and listing its service-methods:

`dir(client.service)`

I get:

`['GetAktuellerStandTageskontingent', 'GetBilanzierungsgebiete', 'GetKatalogwerte', 'GetListeKatalogkategorien', 'GetLokaleUhrzeit', 'GetLokaleUhrzeitMitAuthentifizierung', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__self_class__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__thisclass__']`

Functions break off after 'GetLokaleUhrzeitMitAuthentifizierung'. It appears reading the wsdl-file fails after the comment ().

**Comment by makulatur** [comment]
If this is still of interest to you, @FabianJetter, or any others: I've found another solution for the `ValueError` that does not require patching `isodatetime` but instead truncates the nanoseconds from the response:

```python
import isodate
from zeep.xsd.types import builtins as xsd_builtins_types

def parse_date(_, value):
    # stripping nanoseconds 
    if len(value) == 27:
        value = value[:-8]

    # original function
    if len(value) == 10: 
        value += "T00:00:00"
    return isodate.parse_datetime(value)

xsd_builtins_types.DateTime.pythonvalue = parse_date

session = Session()
```
[Source](https://github.com/mvantellingen/python-zeep/issues/522#issuecomment-427758249)

**Comment by pgm-master** [comment]
> If this is still of interest to you, @FabianJetter, or any others: I've found another solution for the `ValueError` that does not require patching `isodatetime` but instead truncates the nanoseconds from the response:
> 
> ```python
> import isodate
> from zeep.xsd.types import builtins as xsd_builtins_types
> 
> def parse_date(_, value):
>     # stripping nanoseconds 
>     if len(value) == 27:
>         value = value[:-8]
> 
>     # original function
>     if len(value) == 10: 
>         value += "T00:00:00"
>     return isodate.parse_datetime(value)
> 
> xsd_builtins_types.DateTime.pythonvalue = parse_date
> 
> session = Session()
> ```
> 
> [Source](https://github.com/mvantellingen/python-zeep/issues/522#issuecomment-427758249)

<could you please explain the line session = Session() ?

**Comment by pgm-master** [comment]
Hi guys,
I am a newbie to python programming and also in the Marktstammdatenregister. I have been writing some scripts to get the data using GetEinheitWind and has been able to get the data for a limit of 10. But when i tried with the limit of 500, executes  error message
Traceback (most recent call last):
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\xsd\types\complex.py", line 194, in parse_xmlelement
    elements, schema, name, context=context
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\xsd\elements\indicators.py", line 609, in parse_xmlelements
    xmlelements, schema, name, context=context
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\xsd\elements\element.py", line 207, in parse_xmlelements
    % (element_tag.text, self.qname.text)
zeep.exceptions.UnexpectedElementError: Unexpected element '{https://www.marktstammdatenregister.de/Services/Public/1_2/Modelle}NetzbetreiberpruefungStatus', expected '{https://www.marktstammdatenregister.de/Services/Public/1_2/Modelle}LokationMastrNummer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Lakshman.Krishnan/PycharmProjects/untitled/einheit_test_500.py", line 68, in <module>
    c = c.GetEinheitWind(apiKey=apiKey, marktakteurMastrNummer=myMastrNr, einheitMastrNummer=i)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\proxy.py", line 45, in __call__
    kwargs,
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\wsdl\bindings\soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\wsdl\bindings\soap.py", line 197, in process_reply
    result = operation.process_reply(doc)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\wsdl\bindings\soap.py", line 396, in process_reply
    return self.output.deserialize(envelope)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\wsdl\messages\soap.py", line 94, in deserialize
    body_result = self._deserialize_body(body)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\wsdl\messages\soap.py", line 425, in _deserialize_body
    result = self.body.parse(xmlelement, self.wsdl.types, context=context)
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\xsd\elements\element.py", line 130, in parse
    schema_type=self.type,
  File "C:\Users\Lakshman.Krishnan\PycharmProjects\test\lib\site-packages\zeep\xsd\types\complex.py", line 199, in parse_xmlelement
    raise XMLParseError(exc.message)
zeep.exceptions.XMLParseError: Unexpected element '{https://www.marktstammdatenregister.de/Services/Public/1_2/Modelle}NetzbetreiberpruefungStatus', expected '{https://www.marktstammdatenregister.de/Services/Public/1_2/Modelle}LokationMastrNummer'

Any healp would be appreciated. 
Thanks @Ludee @FabianJetter for your valuable comments and help.

**Comment by DBFZmdotzauer** [comment]
Regarding to the post from 4th of February 2019 i would like to ask which SSL-related errors occur in detail, because I run also into error messages behind the companies firewall: 
_HTTPSConnectionPool(host='test.marktstammdatenregister.de', port=443): Max retries exceeded with url: /MaStRAPI/wsdl/mastr.wsdl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (ssl.c:1056)')))_
I already try to donwload the certificates from the MaStR manually and add the root-certificate-chain to the cacert.pem-file but that doesen't fix my problems. Any hints how to avoid SSL-problem under proxy-settings ware welcome.

**Comment by DBFZmdotzauer** [comment]
Found a solution within the IT Support in my company. One option would be to accept all certificates with _session.verify = False_ and another one is to use a local certificate. Under https://docs.python-zeep.org/en/master/transport.html the procedures were described.
best regards Martin

**Comment by lrausch** [comment]
Has anyone used placeholders like * or ? to download filtered data?
I'm trying to use GefilterteListeStromErzeugerRequest with special filter settings like the ones used at the web interface.
best regards Lothar

**Comment by gplssm** [comment]
I do not exactly understand what you're trying to do. Do you want to use wildcards for some of the filtering options in order to not apply this filter?

In addition, I don't know how you access the MaStR webservice. I assume you the function `GetGefilterteListeStromErzeuger` of the [webservice API](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/Funktionen_MaStR_Webdienste_V1.2.39.html). Correct?

We've created this package for easier access to the MaStR data. As fundamental layer, [MaStRAPI](https://open-mastr.readthedocs.io/en/dev/download.html#mastr-api-wrapper) wraps the MaStR webservice functions in python methods, that can be used like

``` python
from open_mastr.soap_api.download import MaStRAPI

mastr_api = MaStRAPI()
mastr_api.GetGefilterteListeStromErzeuger(postleitzahl="10999", limit=3)
```

All unspecified options are then treated as not-to-be-filtered (like * wildcard in bash).

Consider to use [MaStRDownload](https://open-mastr.readthedocs.io/en/dev/download.html#bulk-download) for bulk download.

Please note, I'm referring to code in the `dev` branch here.

**Comment by lrausch** [comment]
I'm currently using delphi for downloading the power plants. 
Using Phython it would be something like 

mastr_api.GetGefilterteListeStromErzeuger(ort="Ham*")

**Comment by gplssm** [comment]
Now, I get it! But sadly I can't help. Maybe it's possible using regular expressions or similar, but that's just a guess. Anyways, it must have been implement server side...

**Comment by lrausch** [comment]
New version of API will be available @08/04/2021
https://www.marktstammdatenregister.de/MaStRHilfe/subpages/webdienst.html
https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/Release-Termine.pdf

A new download option is planned
https://www.marktstammdatenregister.de/MaStRHilfe/subpages/datendownload.html

**Comment by chrwm** [comment]
The new [version ](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/WSDL_Patchnotes_V1.2.74.xlsx
)of the API does not require any changes in the code.
