### ISSUE TITLE
Update postprocessing scripts and data analyses

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#101]

**Comment by Bachibouzouk** [comment]
The improvements of the plots are in the branch `feature/improve_map_plots` which share the history with the current branch until caae51e1b6dce34640b6335206aa65f95779d7a6 (only 5097749 is different). There is a merge conflict, the best way to solve it is to copy paste the cells you want to keep. FYI I only changed thinks at the end of the file after the title "Summen pro Bundesland".

**Comment by gplssm** [comment]
Closed by #106 and #107
