### ISSUE TITLE
Move power_unit_list_len of technolgies in file

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#112]
Remove number of units per technology from main.py file and load from file [versions.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/dev/soap_api/versions.md).
Maybe use a .yml file. This would help creating test.

Minor issue: if power_unit_list_len is less (e.g. 1000) than pu_limit (2000) is still used.
So not possible to download less.

**Comment by gplssm** [comment]
List length is not required anymore. For a complete download, the max. number of units is determined during download since #137
