### ISSUE TITLE
Revise ConfigParser and config read from .yml

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#122]
During #120 I found potential improvements for handling of config files and data. For a re-organization,please consider the following aspects

- re-organize config objects
  - `config_package`: for axample project dir structure
  - `config_project`: config read from project home dir with file names, paths, data version
  - `credentials`: for now, only MaStR-API credentials
- [RawConfigParser](https://docs.python.org/3.4/library/configparser.html#rawconfigparser-objects) is a legacy variant of [ConfigParser](https://docs.python.org/3.4/library/configparser.html#configparser.ConfigParser). Replace by the latter
- create package internal project dir paths/files config object (see WindNODE_ABW for example). Use this object in config.py to 
- Include `.yml` configs into ConfigParser `config_project` [via dict](https://docs.python.org/3.4/library/configparser.html#configparser.ConfigParser.read_dict)

**Comment by chrwm** [comment]
Not clear what is meant and if this is already implemented or needed. Re-open if necessary.
