### ISSUE TITLE
re-include flake8 and pylint in CI configuration

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#134]
flake8 and pylint where [comment out](https://github.com/OpenEnergyPlatform/open-MaStR/blob/94a7518e40e8997b1cd92a779ed3d4cbffe6d5e6/.travis.yml#L13-L18) in #132 due to messy code producing a lot of messages. Once this is cleaned up a bit, re-activate both

**Comment by chrwm** [comment]
Travis configuration file was removed. 848c866be98c720c1a7f8b714e169a403e2e9c56
