### ISSUE TITLE
Move code to more central place

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#169]
- `MaStRDownload._unit_data_specs`
- `MaStRDownload._additional_data_primary_key`
- `open_mastr/soap_api/metadata/` to `open_mastri/metadata/`
- `MaStRMirror.unit_type_map`
- (maybe) `MaStRMirror.orm_map`

The above list is incomplete!

**Comment by chrwm** [comment]
Refactoring remains unclear.
