### ISSUE TITLE
Adapt MaStRDownload.download_power_plants() to be working with postprocess()

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#175]
**Tasks**

- [ ] Replace column renaming in `MaStRDownload.download_power_plants()` by renaming pattern used in `MaStRMirror.to_csv`
- [ ] Adapt documentation `postprocessing.rst` and remove warning about data from `MaStRDownload.download_power_plants()`

**Comment by FlorianK13** [comment]
Seems outdated
