### ISSUE TITLE
Split postprocessing into data cleansing and enrichment

### ISSUE THREAD

**Issue by gplssm** [OpenEnergyPlatform/open-MaStR#176]
Data cleansing

- Unplausible nominal power correction
- Filtering duplicates (expects raw data including all StatistikFlag A and B units)

Enrichment

- Add geom column and fill with data from lat/lon and PLZ

By doing this, parts of the code might be translated to python if that eases the process (as done for geom column creation).

**Comment by FlorianK13** [comment]
With v 0.11.0, cleansing is done when reading data into the database. Seperately, postprocessing scripts can then be applied later. They can be found in the github repository, postprocessing folder.
