### ISSUE TITLE
Help with aggregation of data

### ISSUE THREAD

**Issue by mainrs** [OpenEnergyPlatform/open-MaStR#200]
Hello!

I am currently working with the MASTR data dumps that the website provides and was hoping that someone could help me out with a question I had:

I aggregated all available `Wind-Einheiten` in Germany by filtering for their `Inbetriebnahmedatum` and their `Einheitenbetriebsstatus` to make sure that I only target onshore units that are build until 2020-12-31 and are actually active.

Now comes the part I don't really understand and where official documentation falls short:
Some units' MASTR-ID start with `SEE` and some with `SME`. If I filter for `SEE`-IDs only I get 54GW of installed power, which seems to be close with statistics I've found about 2020.
However, I've read that `SME` are merely older IDs that have been around before MASTR changed their ID system. It doesn't state anywhere that these are obsolete units or units that aren't active anymore.

If I keep them and aggregate the installed power, I get around 100GW, which is way to high.

Maybe someone here does have more knowledge and can (hopefully) help me out! Thanks!

**Comment by Ludee** [comment]
Dear @mainrs, sorry for the late response. I answered parts of the question here: https://github.com/OpenEnergyPlatform/open-MaStR/issues/4#issuecomment-508740414

> The old "EEG Anlagenregister" is discontinued. They were transferred and can be identified by the first letters of the MaStR-ID. "SME.." = old, "SEE.." = new entries.

There is another needed column now called `NichtVorhandenInMigriertenEinheiten` (boolean). 

> Angabe über das Nichtvorhandensein in den migrierten Einheiten

So if the field is `True`, there is no entry in the old register. If it is `False` it is a duplicate.

**Comment by Ludee** [comment]
In older versions this column was called `StatistikFlag`.
See https://github.com/OpenEnergyPlatform/open-MaStR/issues/180

**Comment by chrwm** [comment]
The issue seems to be solved. If not, please reopen it again.
