### ISSUE TITLE
Full Data Download as xml-files

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#201]
Bundesnetzagentur is offering a download of the whole Marktstammdatenregister (see https://www.marktstammdatenregister.de/MaStR/Datendownload). This makes the creation of a full download feature possible, where the whole MaStR is downloaded to a local SQL database. It doesn't seem that such a feature is already included in the package, or is it? Otherwise, is anyone else already working on such a feature?

**Comment by nesnoj** [comment]
Hey @FlorianK13, we are aware of this recently introduced feature and wondering why they didn't provide it from the very first day. We've implemented a parser to extract the XML (not part of open-MaStR yet) and are currently comparing data quality and extent with the those obtained via API.

We'll keep you updated..

**Comment by Ludee** [comment]
Hi @FlorianK13, I just added a first running version of the XML parser to this branch:
https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature-%23202-xmlparser

We would be very happy if we join effort and start developing together. If you wish I can grant you the rights to the repo.

**Comment by nesnoj** [comment]
Thanks @Ludee! Are you up to create some issues on the integration and features? E.g.

- Features: structure, fields, output, relations, ...
- Integration: coexistence of both ways of data acquisition: data storage (to the exisiting DB?), installation (without current docker?), cleansing (application of current methods?), create relations (are there models in the API version than can be used?), ...

Unfortunately I don't have much time to contribute, looking forward to a proposal :). Maybe the merge of both tools can be postponed and only the most important features integrated to see if it's worth the effort..

**Comment by Ludee** [comment]
The comparison of the two methods is ongoing. 
After we have the first results we will decide how to proceed.
I think we will delegate the development to somebody else, I'm busy, too ;)

**Comment by FlorianK13** [comment]
The work on that topic was started, see #202
