### ISSUE TITLE
Fiona Installation on Windows

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#204]
Fiona cannot be installed with pip install on windows -> see https://fiona.readthedocs.io/en/latest/README.html#installation
For windows users, this will lead to an installtion error when trying pip install open_mastr, right?

**Comment by FlorianK13** [comment]
One workaround is to tell windows users that they have to pre install fiona via
conda install -c conda-forge fiona

**Comment by chrwm** [comment]
Yes, sorry, there're some more bugs on the windows installation known.
Could you install it successfully, or are you still running into problems?
Other problems known are

- [x] problem installing numpy 1.21.0 needs python >=3.7 -> solution: install manually, fix python version in requirements
- [ ] problem installing shapely -> solution: intall shapely manually
