### ISSUE TITLE
Update CI / CD 

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#208]
The pipeline for Continous Integration / Continous Delivery has to be updated. There is already some work done, that can be found in [workflows](https://github.com/OpenEnergyPlatform/open-MaStR/tree/dev/.github/workflows). This has to be reviewed and adapted.

**Comment by chrwm** [comment]
Hi @deniztepe if you're working tomorrow, we could have a short meeting to check whether my commit resolved the issue of `test_credentials.py` failing and what are further steps.

**Comment by deniztepe** [comment]
Hi, I am trying to make the ci workflow run, currently on branch 'ci-test'. I am stuck with an error about logger file. `tests/preparation.py` is the first script to run and it triggers a lot of imports from import and so on. I hope you can find the current error log at workflow report CI-Test 7 : https://github.com/OpenEnergyPlatform/open-MaStR/actions/runs/2051863904

You can write here if you have any suggestions.

**Comment by FlorianK13** [comment]
@deniztepe The CI fails currently. Can you check why that's the case?

**Comment by FlorianK13** [comment]
Using pytest on the test functions by @chrwm on Linux resolved in most of the tests failing.

**Comment by deniztepe** [comment]
CI/CD pipeline is currently working. Should we close the issue?
