### ISSUE TITLE
Add CITATION.cff with list of authors

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#218]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by Ludee** [comment]
Output of the first version:
> Hülk, L., ?, G., ?, C., & Kotthoff, F. (2019). open-MaStR (Version 0.9.0) [Computer software]. https://github.com/OpenEnergyPlatform/open-MaStR/

I did not add the last names of @gplssm and @chrwm since they are not in the GitHub profile.
Are you OK of adding your full name to the repo for citation?
Who should we include as well?

**Comment by FlorianK13** [comment]
@deniztepe Should also be added.

**Comment by Ludee** [comment]
> Hülk, L., , G., , C., Kotthoff, F., & Tepe, D. (2019). open-MaStR (Version 0.9.0) [Computer software]. https://github.com/OpenEnergyPlatform/open-MaStR/

**Comment by gplssm** [comment]
> Output of the first version:
> 
> > Hülk, L., ?, G., ?, C., & Kotthoff, F. (2019). open-MaStR (Version 0.9.0) [Computer software]. https://github.com/OpenEnergyPlatform/open-MaStR/
> 
> I did not add the last names of @gplssm and @chrwm since they are not in the GitHub profile. Are you OK of adding your full name to the repo for citation? Who should we include as well?

You can use my last name for the citation :)
