### ISSUE TITLE
Update metadata for latest data release and latest OEMetadata version

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#219]
Please provide a current version of the resulting data as CSV files.

**Comment by FlorianK13** [comment]
@chrwm csv files can now be generated with

db = Mastr()
db.download()
db.to_csv()

**Comment by deniztepe** [comment]
Hi @chrwm, I pushed with the last two commits c4b6b5392b1a3a17664c73776847cdab40785c56 und 12782bf70a32eae839291f9fa86f4a17bf1ccf82 a new function to recreate the basic_units table after a bulk download. After that the `open_mastr.soap_api.mirror.MaStRMirror.to_csv` method works fine. The export process take up to 20 minutes. I adapted also the script `open_mastr/soap_api/scripts/mirror_mastr_csv_export.py` , where you can find a usage example. Please return, if it works or not. 

I also had to rename a column in `basic_units`, which had a typo. Hope it makes sense to you, too.

**Comment by FlorianK13** [comment]
@deniztepe A newer version of json metadata will appear soon. Can you have a look at the function that creates the csv files for the documentation so that it will use the newest json?

**Comment by deniztepe** [comment]
Currently the metadata is extracted from `open_mastr/soap_api/metadata/datapackage.json`. The path to the data package is hardcoded at `open_mastr/soap_api/config.py:215`. Either the new file should replace the current datapackage or the path should be adapted to the new file `datapackage_151.json`. @chrwm Is the new version already final?

**Comment by chrwm** [comment]
Contentwise the metadata is ready, besides #224 adding the copyright information to the metadata. @Ludee is currently formatting them to make them JSON conform. However, I think it still needs to be pushed from @Ludees end.

**Comment by Ludee** [comment]
metadata is ready.
