### ISSUE TITLE
Introduce CalVer for data versioning

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#221]
Calendar Versioning: https://calver.org/
Data Version: https://github.com/OpenEnergyPlatform/open-MaStR/blob/dev/open_mastr/soap_api/config/data.yml

Besides the software versions of this project there are always corresponding data versions.
In semantic versioning, this is now Major Version 3.
In my opinion it would make sense to switch to calendar versioning, since the data is a snapshot from a specific date.

**Comment by chrwm** [comment]
The calendar versioning makes sense to know when the data was produced. 
An additional `id` that highlights the software version (method) that was used to download the data should be added somehow.

**Comment by Ludee** [comment]
[I added a new data version and moved the file to docs folder.](https://github.com/OpenEnergyPlatform/open-MaStR/blob/release-0.11.0/docs/data-release-notes.md#dataversion-2022-05-25_a)
