### ISSUE TITLE
Version 0.10.0 and two unreleased versions in changelog

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#222]
In the [changelog file](https://github.com/OpenEnergyPlatform/open-MaStR/blob/feature-%23202-xmlparser/CHANGELOG.md) there is currently already one description for 0.10.0 and one unreleased version. I added our changes to a second unreleased version. How do we proceed here?

**Comment by Ludee** [comment]
I would suggest to bundle all unreleased and continue with the next release.

**Comment by Ludee** [comment]
Decided to continue with version **0.11.0**.
