### ISSUE TITLE
Parameter empty_schema in Mastr init does not work

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#227]
The parameter empty_schema in the __init__ of the Mastr class has a default value of False. If it is set to True, it raises a sqlalchemy.exc.OperationalError. Do we need this parameter? What is the intention of setting the parameter to True or to False?

**Comment by chrwm** [comment]
The parameter is related to the soap_API and is used to delete all existing tables in the postegre DB & docker container setup before starting the download process. I'm unsure what the initial intention of the parameter was, one could simply build another docker container for the same purpose. Hence, I'm unsure whether to delete it. I'll have a look and come back to you.
Independently on whether to delete it or not, the default should be set to `False` in my opinion.

**Comment by FlorianK13** [comment]
If empty_schema is set to true, a sql query "DROP SCHEMA IF EXISTS" is run. If I remember correctly, sqlite does not have SCHEMA, this is a postgres functionality. So with the current idea to first set up a sqlite database, the parameter should not be allowed to be True.

I would suggest to delete the parameter and the if empty_schema loop in the _initialize_database function (Mastr method).

**Comment by chrwm** [comment]
> So with the current idea to first set up a sqlite database, the parameter should not be allowed to be True.

I agree with this, but I don't see a problem when the default is already on `False`?

> I would suggest to delete the parameter and the if empty_schema loop in the _initialize_database function (Mastr method).

The only risk I see is if people set the parameter manually to `True` in their scripts without knowing what they're doing. I'd not delete the parameter not to deprive features of the soap_API. 
I can address this specifically in the documentation additionally to the existing information on the parameter.

**Comment by FlorianK13** [comment]
Within the soap_api the parameter would still exist (it is still a parameter in mastr_mirror). Right now, when running the download(method="API") function, the mastr_mirror is called with a hard coded empty_schema=False.

But we should delete the possibility to set empty_schema in the mastr.__init__, since we cannot have paramters there that do not work.

**Comment by chrwm** [comment]
Ok, go ahead and delete it. Updating  the sqlite DB with the soap_API seems to have additional problems I'm currently looking into.

**Comment by FlorianK13** [comment]
The parameter is not in the `Mastr.__init__` anymore.
