### ISSUE TITLE
Update install documentation

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#230]
I was not able to start the software from the current state of the documentation.
The installation instructions need to be updated.

**Comment by FlorianK13** [comment]
@Ludee Have you tried to pip install it?

Just run 
`pip install -e .`
within the root folder.

**Comment by Ludee** [comment]
The current version has good instructions to run the code.

Perhaps we add one of the final images that show the workflow to the documentation in #203

**Comment by FlorianK13** [comment]
Actually none of the workflows in #203 are up-to-date. As mentioned in #301 we want to shrink the number of parameters in the download method. Then we will also update the documenation.
