### ISSUE TITLE
Improve documentation for API

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#231]
- [x] The documentation for setting DB_ENGINE needs to be improved
- [x] Fix data description tables

**Comment by FlorianK13** [comment]
Does DB_ENGINE right now need a description? Because we cannot set it to Docker since that is not implemented yet.

**Comment by chrwm** [comment]
I tend to say that we don't need a more detailed explanation than [14cfce0](https://github.com/OpenEnergyPlatform/open-MaStR/commit/14cfce09368c97d4ad21e8bd240f0104861b8da3) just yet because the parameter is not part of the function `download()` in mastr.py. Hence, from a mere user perspective, the code pieces currently there should be of no concern nor influence the usability.
From a dev perspective, this might be different.

**Comment by FlorianK13** [comment]
Sounds good. I would say that the functionality to set up a Docker database will be part of 0.11.1

**Comment by chrwm** [comment]
- [ ] Describe csv export

**Comment by FlorianK13** [comment]
Will be further discussed in #344
