### ISSUE TITLE
Add Download bar for jupyter notebook

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#232]
Many users will run the code in jupyter notebook. Here the download bar is not visible for the bulk download, which is not good since it gives the user feedback (and stops him/her from aborting the download after a few minutes). Maybe we can use another download bar package (instead of clint.textui.progress)

**Comment by FlorianK13** [comment]
And we should not forget to change the dependencies in setup.py if we use another package.

**Comment by FlorianK13** [comment]
Apparently Linux bash Terminal also does not show a download bar.

**Comment by chrwm** [comment]
With 556d0f6, it now works on Linux.
