### ISSUE TITLE
Data description for sqlite database

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#233]
The current data description is about the generated csv files. It does not describe the tables in the sqlite database. We should at least prominently name all tables that are generated within the database, so that users can explore them by themself using pandas.

**Comment by FlorianK13** [comment]
@chrwm Do you think the current naming of the tables in 'Getting started' is enough? Or does it need more description?

If you think it's enough you can close the Issue.

**Comment by chrwm** [comment]
I think the current structure and description, for now, are enough.
