### ISSUE TITLE
Add main.py to run scripts

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#236]
- [x] Add a first version @Ludee 
- [x] Improve and add more comments
- [ ] Include postprocessing

**Comment by Ludee** [comment]
Did you change anything yet @chrwm?
Let's keep this issue for the next release.

**Comment by chrwm** [comment]
I'm not sure what you meant with postprocessing, but the export of cleaned csv's is now included in main.py.

**Comment by FlorianK13** [comment]
Postprocessing will be implemented in the future and will not be part of `main.py`
