### ISSUE TITLE
Combustion_extended table not filled

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#248]
It seems that the combustion table is not filled when parsing the xml files.

**Comment by Ludee** [comment]
I have the same issue but with 28 entries in the table.

**Comment by deniztepe** [comment]
It seems that the file 'EinheitenVerbrennung.xml' is falsely mapped to the technology 'electricity_consumer'. I will push the correction as soon as possible after the develop branch is up to date. If one does not specify the technology parameter for bulk download, everything should be fine. But with the current main.py, not all the tables are filled with data. This raises the problem, that api and bulk method accept different set of selection for technology parameter, although it is only one parameter. Either the condition should be documented or the method should be edited or the technology parameter can be seperated into two params.

**Comment by deniztepe** [comment]
Bugfix is successfully merged by PR #253 .
