### ISSUE TITLE
Methods bulk and API accept different sets of technology selections

### ISSUE THREAD

**Issue by deniztepe** [OpenEnergyPlatform/open-MaStR#252]
Although the two methods use the same parameter `technology`, the bulk method accepts selections like 'electricity_consumer' or 'grid', where as API does not. These are defined under open_mastr/orm/bulk_technologies. That is why a regular usage without specifying the technologies works. To reproduce the error you can try: 
```
db = mastr()
mastr.download(method="API", technology="grid")
```

My suggestion would be either expand the documentation for clearance or split the technology parameter into bulk_technology and api_technology

- [x] Decide how to proceed
- [ ] Make changes
- [ ] Documentation
- [ ] Adapt and expand test cases

**Comment by Ludee** [comment]
From my point it would make sense to improve the API function to also deal with the missing technologies.
Is that a feasible solution?

**Comment by chrwm** [comment]
I'll check if the API delivers the missing technologies and look at a potential implementation.

**Comment by chrwm** [comment]
The affected specifications for parameter `technology`, that work in with `method` _bulk_ but not _API_, and possible solutions are:

- [x] electricity_consumer
rename "consumer" to "electricity_consumer" in https://github.com/OpenEnergyPlatform/open-MaStR/blob/965978d15d6d349f7c3ed56e787d0fce87031757/open_mastr/soap_api/download.py#L545-L547
- [ ] balancing_area 
needs new implementation, [GetBilanzierungsgebiete](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/2022-04_21_Dokumentation_MaStR_Webdienste_V1.4.1.pdf#page=46), [Bilanzierungsgebiet](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/2022-04_21_Dokumentation_MaStR_Webdienste_V1.4.1.pdf#page=670)
- [ ] market
needs new implementation, [GetMarktakteur](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/2022-04_21_Dokumentation_MaStR_Webdienste_V1.4.1.pdf#page=58)
- [x] permit 
is not handled as technology. Is handled as its own table structure in orm.py and handled in function https://github.com/OpenEnergyPlatform/open-MaStR/blob/965978d15d6d349f7c3ed56e787d0fce87031757/open_mastr/soap_api/mirror.py#L583-L587
possible quick solution, in mastr.py: 
```
if method=="API" and technology=="permit":
  api_data_types.append("permit_data")
  technology.remove("permit")
  ...
 
```
- [x] location 
is not handled as technology. Is handled as its own table structure in orm.py and handled in function https://github.com/OpenEnergyPlatform/open-MaStR/blob/965978d15d6d349f7c3ed56e787d0fce87031757/open_mastr/soap_api/mirror.py#L722-L726

possible quick solution, in mastr.py: 
```
if method=="API" and technology=="location":
  technology.remove("location")
  api_location_types = [
    "location_elec_generation",
    "location_elec_consumption",
    "location_gas_generation",
    "location_gas_consumption",
]
  ...
 
```

- [ ] gas
- [ ] grid

**Comment by FlorianK13** [comment]
> possible quick solution, in mastr.py:
  if method=="API" and technology=="location":

Here you'd have to check if technology is a string or a list. If second case is true, it rather needs a 
`if "location" in technology:`

**Comment by FlorianK13** [comment]
@chrwm How far is this feature branch, can we already merge it or is there something missing? 
I'm asking since the merge conflicts will become harder to solve for older feature branches.

**Comment by chrwm** [comment]
There are still some more functions to implement. 
- gas
- grid 
- balancing area
- market

I was waiting for the refactoring to finish to avoid merge conflicts. This seems to be the case now, so I'll continue.

**Comment by FlorianK13** [comment]
We should probably rename `technology` with `tables`, since it can now include strings like 'permit', 'locations',...

**Comment by chrwm** [comment]
I generally agree that `technology` is not an adequate parameter name anymore.
I think `tables` could be too generic, as you only understand what is meant if you know the underlying database table structure.
I think `Stammdaten` could be good, as it fits the technologies as well as the other information on offer. However, in English, a possible translation is `master data`, so maybe `mastr_data` could be nice?

**Comment by chrwm** [comment]
From current discussions: `mastr_data` could be confusing. Simplify to `data`.

**Comment by FlorianK13** [comment]
Maybe also add a table in the documenation telling the user which string in `data` is possible for bulk or API download

| string | bulk | API |
|--------|------|-----|
| wind   | yes  | yes |
| solar  | yes  | yes |
| grid   | yes  | no  |
