### ISSUE TITLE
Plan public outreach for release

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#255]
To promote the release v0.11.2 we should publish the news on different channels, e.g.

- [x]     strommarkttreffen
- [x]     openmod-initiative.org
- [x]     climate Change AI
- [x]     [fortiss ](https://www.fortiss.org/ergebnisse/software/open-mastr)
- [x]    twitter
- [x]     update [RLI website](https://reiner-lemoine-institut.de/news-datensatz-marktstammdatenregister-bnetza//)

**Comment by FlorianK13** [comment]
Maybe also here:
https://towardsdatascience.com/tagged/open-data

**Comment by FlorianK13** [comment]
Short post at climatechange AI:
https://community.climatechange.ai/c/power-and-energy-systems/huge-data-set-on-german-energy-system

**Comment by FlorianK13** [comment]
We have generated some outreach.
