### ISSUE TITLE
Document download limitation from marktstammdatenregister.de

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#256]
I have experienced now for a few times that the server from marktstammdatenregister.de sets a download speed limitation. At those times the bulk download works only with ~10kB/sec and needs several hours. Should we monitor the speed and give out a warning to the user if the speed is too slow.

"Warning: Currently the servers from marktstammdatenregister have restricted the download speed. Please try it again another time:"

**Comment by chrwm** [comment]
I've experienced the same already, too. I think the warning is a good idea in that case.
