### ISSUE TITLE
Create a "How To Postprocessing"

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#263]
We need to tidy up the postprocessing folder. Then we need to define how a postprocessing notebook has to look like. Especially a criterion for

- [ ] ~name of the notebook~
- [ ] where to put the dependencies (each package with a clearly definded version)
- [ ] Will others be able to contribute a postprocessing notebook via PR?

**Comment by Ludee** [comment]
We just decided to only develop the sqlalchemy postprocessing.
The Jupyter Notebooks and SQL-scripts are outdated and will be moved to a deprecated folder.
The tasks is to define a template for a general workflow.

**Comment by FlorianK13** [comment]
Not relevant anymore, can be reopened if needed.
