### ISSUE TITLE
API export for solar fails due to low memory

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#269]
When exporting the tables with the soap api, sometimes the export runs low on memory and fails.
Adapt the export function to avoid this.

**Comment by deniztepe** [comment]
Aktuell wird pd.DataFrame.to_csv() benutzt. Die Funktion hat auch chunksize parameter. Könnte das eine Lösung sein?
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html?highlight=to_csv#pandas.DataFrame.to_csv

**Comment by FlorianK13** [comment]
Closed with #306
