### ISSUE TITLE
Calling API download with limit

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#278]
When I run the following program for the first time, it downloads two new entries to the database. This is as expected, since I set limit=2.

If i run the same program again, it does not download two more units (as I would have expected). Instead it does not change the databse at all and does not add new entries. Is that intentional?

# Code

date = None
limit = 2
chunksize = 1000
technology = ["solar"]
data_types = ["unit_data", "eeg_data", "kwk_data", "permit_data"] 
location_types = [
    "location_elec_generation",
    "location_elec_consumption",
    "location_gas_generation",
    "location_gas_consumption",
]

db = Mastr()
db.download(
    method="API",
    api_limit=limit,
    api_chunksize=chunksize,
    technology=technology,
    api_date=date,
    api_processes=None,
    api_data_types=data_types,
    api_location_types=location_types
)

**Comment by FlorianK13** [comment]
I tested it on develop branch.

**Comment by chrwm** [comment]
This does not seem to be a problem anymore. Reopen if necessary.
