### ISSUE TITLE
Add black formatting as CI

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#291]
Should we add a black formatting github action like described in this video (at 6:36) https://www.youtube.com/watch?v=j1MbEYhYj_Y

**Comment by FlorianK13** [comment]
Then we could delete the flake8 and pylint files from the main directory

**Comment by deniztepe** [comment]
Seems like a good automation, instead of apply black commit. I didn't really unterstand when exactly are the black formatting applied, but i can implement it on the feature branch and we can look how it behaves.

**Comment by FlorianK13** [comment]
What do you think @chrwm ?

**Comment by chrwm** [comment]
From the option presented in the video I'd prefer an implementation as a pre-commit hook to see the changes locally before comitting.

**Comment by FlorianK13** [comment]
All done
