### ISSUE TITLE
API download of location data is erroneous

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#301]
Several things concern me about the location download from the API. They probably have to be modified:

- [x] additonal_locations_requested seems not to get filled properly
- [x] additonal_locations_requested still inherits from ParentTables and hence has the `DatenQuelle` and `DatumDownload` column
- [x] `location_basics` gets filled with only a few units
- [x] `location_extended` does not get filled at all
- [x] See if the problem from #279 still exists

**Comment by FlorianK13** [comment]
@chrwm I think with the new function `technology_input_harmonisation` we can no longer give the parameter `api_location_types` to the Mastr.download method, right? This has to be included now as "locations" in parameter `technology`.

I think we have to change the main.py file then and maybe delete this parameter from the Mastr.download method.

https://github.com/OpenEnergyPlatform/open-MaStR/blob/e91f97a9af2e21197996f641e474b8acf8bc7757/open_mastr/utils/helpers.py#L288-L310

**Comment by chrwm** [comment]
We still can. The function checks if `location` is given as input to the _technology parameter_, as would be possible for the bulk download. If that's the case, it's removed from the _technology parameter list_, and the parameter _api_location_types_ is set to all possible location types. 
The fact that this happened is saved in the parameter _harmonisation_log_ and printed as a warning to the user. 
So currently, it's not touching the underlying API code. However, we could revise that if changes become necessary in your current development.

**Comment by FlorianK13** [comment]
But I think the problem is that in this line the parameter `api_location_types` is overwritten with `None` if locations does not appear in `technology`. So right now I think the only way to download location data with the API is to include 'location' in `technology`.

https://github.com/OpenEnergyPlatform/open-MaStR/blob/e91f97a9af2e21197996f641e474b8acf8bc7757/open_mastr/mastr.py#L172-L175

**Comment by FlorianK13** [comment]
@chrwm I think we should discuss this next monday. I also think that the name `technology` does not fit anymore and that we should also remove some parameters from the `Mastr.download` method.

**Comment by chrwm** [comment]
> But I think the problem is that in this line the parameter api_location_types is overwritten with None if locations does not appear in technology.

True, handing over the parameter _api_location_types_ to technology_input_harmonisation() is missing in case `location` is not specified but _api_location_types_. Let's speak about it on Monday how to better harmonise API & bulk functions.

**Comment by FlorianK13** [comment]
One more thing I came across:
Downloading locations is not linked to downloading units. Meaning when I download the data of one specific wind turbine and also want to get the location data of that specific turbine is not possible with the API. I would have to download thousands of random location entries and hope that the one I want appears at some point.

**Comment by FlorianK13** [comment]
Harmonisation of api and bulk parameters is further adressed in #308
