### ISSUE TITLE
Failure API download for biomass: local variable 'inserted_and_updated' referenced before assignment

### ISSUE THREAD

**Issue by aspanc** [OpenEnergyPlatform/open-MaStR#304]
Hi guys,
i found this project today and tried the API download according the documentation. 
`from open_mastr import Mastr`
`db = Mastr()`
```
db.download(
    method="API",
    technology=["biomass"],
    api_data_types=["unit_data","eeg_data","kwk_data"],
    api_limit=1000,
    api_date=None
)

```
And I am getting following result:
![image](https://user-images.githubusercontent.com/109906710/180648617-81bb422f-50bf-4c25-b0a3-d83f4b418656.png)

Is this a bug or a failure on my site?

**Comment by FlorianK13** [comment]
Thanks for sharing your issue @aspanc. I'll try to reproduce the error today.

**Comment by FlorianK13** [comment]
I was not able to reproduce the error. @aspanc Can you do one of the following:
1) Since the API download depends on the availability of the BNetzA API, you can run the same script again. If the API was not available the first time, this could have caused the error. If the same error occures again, just let me know.
2) You can also try to download the data with db.download(method="bulk", technology=["biomass"]), if you are not specifically intersted in data from the API

**Comment by aspanc** [comment]
Thanks for the rapid answer. I am still having the same issue. So maybe there is another failure. I will try further because actually the API functionality is one of my main interests. Probably I made a failure regarding the configuration steps

**Comment by FlorianK13** [comment]
But you have registered at [marktstammdatenregister](https://www.marktstammdatenregister.de/MaStR/Assistent/AuswahlAssistent) and have a proper APIkey? So you have those credentials in the credentials file as described [here](https://open-mastr.readthedocs.io/en/latest/advanced.html#mastr-account-and-credentials)

**Comment by chrwm** [comment]
I was able to reproduce the error on the production branch. 
It seems, as @FlorianK13 says, please check your credentials file. For me, the error occurred when my credentials were wrong or in the incorrect format.
As stated in the documentation, the format of the `credentials.cfg` file in `.open-MaStR/config/` should look like 

``` 
[MaStR]
user = SOM123456789012
token = msöiöo8u2o29933n31733m§=§1n33§304n... # optional, 540 characters
```

The token should be written in one line, without line breaks.

**Comment by FlorianK13** [comment]
Maybe we should implement an API credentials test function that tells the user if his/her credentials do not work @chrwm

**Comment by chrwm** [comment]
Yes, let us do that and let's improve the documentation regarding the topic on the same branch.

**Comment by FlorianK13** [comment]
I have added #307

**Comment by chrwm** [comment]
Ok, I'll restructure and update the documentation section, once you pushed the branch.

**Comment by aspanc** [comment]
Thanks again. The problem has been something with the registration. I have been registered, but something is missing. 
I will try to find out....

**Comment by chrwm** [comment]
@aspanc Thanks for the update. Suppose you encounter further problems, free to open a new issue, including the error message.
