### ISSUE TITLE
API download credential test

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#307]
Should we add a function `test_API_credentials` that checks the credentials of the user when download method= API is selected?
I could imagine a function that tries to download one unit and if it works, it adds a [check] entry to the credentials file?

So every time the download via API is called it looks if the [check] entry is already there and if not, it calls the function `test_API_credentials`

- [ ] implement `test_API_credentials`
- [ ] update documentation (maybe also a clear guide for how to get an API key?)

**Comment by deniztepe** [comment]
Closed with PR #309
