### ISSUE TITLE
get_power_unit() and get_all_units() are the same function

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#31]
**get_power_unit()**
https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L41-L68

**get_all_units()**
https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L71-L89

Only difference is the parameter [_einheitBetriebsstatus_](https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L56).

**Comment by Ludee** [comment]
In fact, the two functions use different API-requests: 
**GetGefilterteListeStromErzeuger** & **GetListeAlleEinheiten**

The function **GetListeAlleEinheiten** sould not be used, because it also contains cosumers and gas units.

**Comment by ghost** [comment]
Removed the option for all units
