### ISSUE TITLE
Import fails during downtime of MaStR

### ISSUE THREAD

**Issue by ghost** [OpenEnergyPlatform/open-MaStR#313]
During maintenance downtimes the import statement does not resolve (frozen)
Standalone scripts do not work with already processed bulk downloads during that time.

**Comment by FlorianK13** [comment]
Hi @c21SF and thanks for your bug report. We have already expirienced this bug and have written a workaround in Pull Request #292 
Since the problem seems to occure more often then we have expected, we should probably have a new release soon
@chrwm @deniztepe

**Comment by FlorianK13** [comment]
PR #292 is merged to develop and will be part of v0.11.5 (#315)
