### ISSUE TITLE
limit parameter in Mastr.to_csv()

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#316]
I do not understand what the parameter `limit` in `Mastr.to_csv` does. 
What can the user do with that parameter?

**Comment by chrwm** [comment]
It can be used to [export ](https://github.com/OpenEnergyPlatform/open-MaStR/blob/8985b40e10f2edead89939af05be30b2c42d77b0/open_mastr/mastr.py#L297-L299)only the first _n_ entries of the technology tables.
