### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#332]
- [x] Switch from .MD to .RST to allow easier formatting
- [x] Update license identifier
- [x] Include link to PyPi and Zenodo
- [x] Add more badges
- [x] Add and align images

**Comment by Ludee** [comment]
Aligne images on top of a RST file is not possible.
The workaround with raw html only works with one image:
https://github.com/github/markup/issues/163

Other related sites:
https://stackoverflow.com/questions/63296956/image-above-title-github-readme-rst
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/images.html

Create one large image with logos and include!

**Comment by FlorianK13** [comment]
Looks very nice already. 
Can you also add the monthly downloads badge?

|PyPI download month|

.. |PyPI download month| image:: https://img.shields.io/pypi/dm/open-mastr?label=PyPi%20Downloads
   :target: https://pypi.org/project/open-mastr/

**Comment by Ludee** [comment]
![MaStR_Readme_Logo](https://user-images.githubusercontent.com/14353512/199113556-4b53660f-c628-4138-8d01-3719595ecda1.png)
