### ISSUE TITLE
python package from pypi does not work

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/open-MaStR#338]
the installed package from pypi (`pip install open-mastr`) does not work, because it does not contain the config files.
They need to be included in the manifest or setup.py.

**Comment by wingechr** [comment]
Steps to reproduce:

in a clean environment: 

* `pip install open-mastr`
* `>>> from open_mastr import Mastr`

results in 

```
FileNotFoundError: [Errno 2] No such file or directory: '.env\\lib\\site-packages\\open_mastr\\utils\\config\\data.yml'
```

**Comment by wingechr** [comment]
suggested fix:

ìn this line:
[            os.path.join("soap_api", "config", "*.yml"),](https://github.com/OpenEnergyPlatform/open-MaStR/blob/58ac0d6c90f4f6492c2ea733417954c6f459434e/setup.py#L70)

needs to be `"utils"` instead of `"soap_api"`

**Comment by chrwm** [comment]
Thanks, @wingechr, for reporting. I tried to reproduce the bug on Linux in a fresh env and tried to run main.py -> 1st code line `from open_mastr import Mastr`, but for me, the script works as expected and starts the bulk download.

Did you try the same, or did you import it somewhere else?

**Comment by wingechr** [comment]
Interesting. must be a platform or python or pip thing:

I am using windows10, python 3.10, pip 22.2.2

after i run `pip install open-mastr` in a clean virtualenv, this is the content of the folder `env\Lib\site-packages\open_mastr\utils`

![grafik](https://user-images.githubusercontent.com/4265368/186617521-7b0caf50-1496-444c-afb8-bed3d30ac7c0.png)

As you can see, the folder `config` with the yml files is missing, because of the wrong line in `setup.py`.

**Comment by chrwm** [comment]
You were right, I was able to reproduce the error now. I'll correct it.
