### ISSUE TITLE
simplify file name methods

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#36]
The filenames ([csv_name](https://github.com/OpenEnergyPlatform/open-MaStR/blob/dev/import-api/utils.py#L29-L60)) is overingeneered.
Set the filesnames for each technology once and import when needed.

The filenames including the data version is needed to ensure data integrity!

**Comment by solar-c** [comment]
solved on branch  feature/remodel_powerunit_download, can be closed upon branch merge into dev
