### ISSUE TITLE
Readme.rst does not work on pypi landing page

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#364]
It seems like the file format .rst does not really work on pypi: https://pypi.org/project/open-mastr/

**Comment by FlorianK13** [comment]
@Ludee Probably interesting for you since you are working in different repositories on that topic.

**Comment by FlorianK13** [comment]
"If your README is written in reStructuredText, any invalid markup will prevent it from rendering, causing PyPI to instead just show the README’s raw source."

From https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by FlorianK13** [comment]
As mentioned in #366, `twine check` can validate that the Readme file shows correctly on pypi (see [here](https://twine.readthedocs.io/en/stable/#twine-check)). If I run the `twine check` command it tells that the test passes, however the Readme does not show correctly on pypi.

I'm a little confused.

**Comment by chrwm** [comment]
For me too, weird. Testing the rst with [restview](https://pypi.org/project/restview/) has some formatting issues with logos. 
Replacing `.. figure:: ` with `.. image::` solve them.

**Comment by chrwm** [comment]
Resolved in https://github.com/OpenEnergyPlatform/open-MaStR/commit/b2e5a04d32df0a7be546ff32ee3a6e3dda28a93c

Display on [Test-PyPI](https://test.pypi.org/project/open-mastr/0.12.1a4/)
