### ISSUE TITLE
README: Broken link to ReadTheDocs

### ISSUE THREAD

**Issue by DSc-de** [OpenEnergyPlatform/open-MaStR#372]
**Issue:**
Broken link in README.rst: 'Find the [documentation](https://open-mastr.readthedocs.io/en/dev) hosted on ReadTheDocs.'

**Proposed Fix:**
Link to [https://open-mastr.readthedocs.io/en/develop](https://open-mastr.readthedocs.io/en/develop) instead of [https://open-mastr.readthedocs.io/en/dev](https://open-mastr.readthedocs.io/en/dev).

However, really link the develop branch? Proposal:
* In production (main) branch: link to default, i.e. [https://open-mastr.readthedocs.io](https://open-mastr.readthedocs.io)
* In develop branch: link to [https://open-mastr.readthedocs.io/en/develop](https://open-mastr.readthedocs.io/en/develop)

**Next Steps:**
I could fix it by means of a pull request, just advise which ReadTheDocs link target to use.

**Comment by chrwm** [comment]
Thanks for pointing out the mistake! 
I fixed the documetation link while fixing the rst file for PyPI. https://github.com/OpenEnergyPlatform/open-MaStR/commit/b2e5a04d32df0a7be546ff32ee3a6e3dda28a93c 
It now points to RTD `latest`, which is associated with the production branch. 

If I didn't need to fix the README.rst, the PR would have been the way to go!
