### ISSUE TITLE
Add pypi-test to `RELEASE_PROCEDURE`

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#376]
We could add the pypi-test to the RELEASE_PROCEDURE. So that if changes were made at README we should test it on the pypi-test server.

**Comment by FlorianK13** [comment]
Maybe we can do that on the release branch

**Comment by chrwm** [comment]
I already added a section on the release branch [here](https://github.com/OpenEnergyPlatform/open-MaStR/commit/f1021346f3b2a44d415bf923dfac961609b4ed85)
