### ISSUE TITLE
Change to static links in README.rst

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#380]
The links to license, contributing and citation in the readme work via markdown referencing. On [PyPI](https://pypi.org/project/open-mastr/#description), however, this won't work, e.g. the link to the license yields: https://pypi.org/project/open-mastr/LICENSE.txt/

- [x] Correct links on release branch for next release

**Comment by FlorianK13** [comment]
Done with #419
