### ISSUE TITLE
Wrong CSV encoding in export of add. tables

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#385]
Extra issue for part 2 of #383

**Comment by chrwm** [comment]
@nesnoj [fba5bb1](https://github.com/OpenEnergyPlatform/open-MaStR/pull/384/commits/fba5bb1402ecbfcbd1672d1de3922a986a337f21) fixed the encoding issue. All csv are exported in utf-8 and pandas has no poblem reading them. I'm currently preparing a new uplaod for Zenodo. However, I realised that the metadata need some updating. https://github.com/OpenEnergyPlatform/open-MaStR/issues/386 Thus, I expect the upload rather at the end of the week.

**Comment by chrwm** [comment]
Fixed by #384
