### ISSUE TITLE
Save deleted units to csv

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#387]
Right now, the bulk download files contain units with duplicated MaStR IDs. Since our databases have a primary key constraint, we cannot write those duplicated units to the database. That's why we delete those units (mainly in solar_extended). We should have a feature where those deleted units are written to a csv file to see what is actually deleted there.

This could be handled by a new parameter in the download function: `save_deleted_units` which is set to False by default.

**Comment by chrwm** [comment]
They are currently saved in the db table `deleted_units` isn't it?

The mapping https://github.com/OpenEnergyPlatform/open-MaStR/commit/64c306ef36c4a10bb7b247963bdff25dcd2169ab I wrote currently exports them, we just would need them to the constant ADDITIONAL_TABLES as potential option. We then export them with help of an additional parameter `save_deleted_units` in "to_csv" or just by inserting the table name in the `tables` parameter?

**Comment by FlorianK13** [comment]
I have adapted the description above. The issue is about units that get deleted within the bulk download procedure, they are independent from the newly introduced `deleted_units` table.

**Comment by FlorianK13** [comment]
I've saved the deleted units to csv files and ran several analyses. To me it seems like they are really just duplicates of existing entries. Hence we can continue to delete them.

**Comment by FlorianK13** [comment]
I'll close this issue but keep the branch for a little longer. If no more troubles appear we can also delete the branch.

I really hope that BNetzA fix this issue in one of their releases of the `Gesamtdatenexport`.

**Comment by FlorianK13** [comment]
I have sent this Mail to BNetzA and will also post the answer here:

Hi,

ich habe eine Frage / Anmerkung zum Gesamtdatenauszug:

In den Tabellen "einheitensolar", "anlageneegsolar", "einheitenstromspeicher" und "anlagenstromspeicher" tauchen einige IDs mehrfach auf. Dies führt zu Problemen bei dem Einlesen in eine Datenbank. 
Beispielsweise wähle ich für "einheitsolar" die Spalte "EinheitMastrNummer" als unique ID. Im Gesamtdatenauszug tauchen dann aber einige Einträge mit derselben "EinheitMastrNummer" auf. 
Ist das beabsichtigt oder ein Fehler? Falls es beabsichtigt ist, was genau ist der Grund dafür?

**Comment by FlorianK13** [comment]
I got the following answer:

Vielen Dank für den Hinweis. Diesen Bug haben wir bereits behoben und werden diesen dann zum nächsten Release in ca. 6 Wochen auf dem live-System beheben. So lange kann es noch zu den von Ihnen beobachteten Problemen kommen.

So it should not be an issue anymore from february 2023 onwards.
