### ISSUE TITLE
Replace numeric value in column `hydro_extended.ArtDerWasserkraftanlage` by name

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#390]
Hey @chrwm, as reported via RC now the corresponding issue:

In the DB table `hydro_extended` the column `ArtDerWasserkraftanlage` is numeric - unique values are: [890, 891, 894, 895, 896, 897]. It'd be helpful to have the name instead such as Laufwasser, Pumpspeicher, ... etc

I couldn't find nothing in the official docs about the mapping, it might be included in the Gesamtdatenexport?

**Comment by nesnoj** [comment]
To allow for a manual fix for my current dump, does anyone have the value->name mapping and could post it here? Maybe you, @FlorianK13 ?

**Comment by FlorianK13** [comment]
Hi @nesnoj 
The mapping is defined in the `katalogwerte.xml` file:
"
<Katalogwert>
        <Id>890</Id>
        <Wert>Laufwasseranlage</Wert>
    </Katalogwert>
    <Katalogwert>
        <Id>891</Id>
        <Wert>Speicherwasseranlage</Wert>
    </Katalogwert>
    <Katalogwert>
        <Id>894</Id>
        <Wert>Wasserkraftanlage in Trinkwassersystem</Wert>
    </Katalogwert>
    <Katalogwert>
        <Id>895</Id>
        <Wert>Wasserkraftanlage in Brauchwassersystem</Wert>
    </Katalogwert>
    <Katalogwert>
        <Id>896</Id>
        <Wert>Abwasserkraftanlage</Wert>
    </Katalogwert>
    <Katalogwert>
        <Id>897</Id>
        <Wert>Meeresenergie</Wert>
    </Katalogwert>
"

**Comment by nesnoj** [comment]
> Hi @nesnoj The mapping is defined in the `katalogwerte.xml` file:
> 
> 890 Laufwasseranlage 88 891 Speicherwasseranlage 88 894 Wasserkraftanlage in Trinkwassersystem 88 895 Wasserkraftanlage in Brauchwassersystem 88 896 Abwasserkraftanlage 88 897 Meeresenergie 88

Great, thanks a lot! :)

**Comment by FlorianK13** [comment]
Closed by #392
