### ISSUE TITLE
Extend Readme with examples that use open-mastr

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#398]
As the wasserstoffatlas.de looks quite nice, we could start collecting those usage examples. What do you think @chrwm @Ludee ?

**Comment by FlorianK13** [comment]
@Ludee @chrwm Do you have links to websites that use open-mastr? Maybe from your research projects?

**Comment by nesnoj** [comment]
I like this idea @FlorianK13 ! Let's start to collect some projects/tools/... here!

- [PV- und Windflächenrechner](https://www.agora-energiewende.de/service/pv-und-windflaechenrechner/) (completed)
- Data pipeline [eGon-data](https://github.com/openego/eGon-data/) in the research project [eGo^n](https://ego-n.org/) (in progress)
- [DigiPlan Anhalt](https://reiner-lemoine-institut.de/digitaler-planungsatlas-anhalt-digiplan/) (in progress)
- [EmPowerPlan](https://reiner-lemoine-institut.de/projekt-empowerplan/) (in progress)
- [EE-Status App](https://ee-status.herokuapp.com/)
- [Wasserstoffatlas](https://wasserstoffatlas.de/)

**Comment by FlorianK13** [comment]
Example projects were added to the `Readme.md`
