### ISSUE TITLE
BNetzA-MaStR

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#4]
## Processed data set: Bundesnetzagentur - Marktstammdatenregister

* 2019-01-31 MaStR is online
* 2019-02-07 Start review
* 2019-03-01 Inofficial release data v1.1

Link to metadata: [supply.bnetza_mastr.sql](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/supply.bnetza_mastr.sql)
Link to API-Infos: https://github.com/OpenEnergyPlatform/open-MaStR/issues/10

Link to Marktstammdatenregister: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStR)
Link to Documentation: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStRHilfe/index.html)
Link to API Documentation: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStRHilfe/subpages/webdienst.html)
WSDL: [.../MaStRAPI/wsdl/mastr.wsdl](https://www.marktstammdatenregister.de/MaStRAPI/wsdl/mastr.wsdl)
Data license: [https://www.govdata.de/dl-de/by-2-0](https://www.marktstammdatenregister.de/MaStR/Startseite/Impressum)
**Data Download**: [reiner-lemoine-institut.de](https://reiner-lemoine-institut.de/datenveroeffentlichung-aus-dem-marktstammdatenregister-der-bundesnetzagentur/)

**status** (number of units / number of units with geolocation)

| version | date | unit | wind | hydro | biomass | solar |
|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| v1.1 | 2019-03-01 | 1862005 | 30566 / 12099 | 7453 / 1725 | 18337 / 11366 | 804365 / 52147 (x1) |
| v1.2 | 2019-03-03 | 1884005 | 31312 / 13166 | 7671 / 1845 | 22873 / 15656 | 1799323 / 103423 (x1) |
| v1.3 | 2019-04-12 | 1965200 | 32920 / 14337 | 8160 / 2166 | 25369 / 17888 | 1861631 / 98152 (x1) |
| v1.4 | 2019-06-11 | 2110197 | 35540 / 16413 | 8602 / 2472 | 26991 / 19214 | tba / tba |
| v1.5 | tba | tba | tba / tba | tba / tba | tba / tba | tba / tba |

 (x1) not included in the release

**Comment by LosWochos76** [comment]
> ## Processed data set: Bundesnetzagentur - Marktstammdatenregister
> * 2019-01-31 MaStR is online
> * 2019-02-07 Start review
> * 2019-03-01 Inofficial release data v1.1
> 
> Link to metadata: [supply.bnetza_mastr.sql](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/supply.bnetza_mastr.sql)
> Link to API tutorial: [BNetzA_MaStR_API.ipynb](https://github.com/OpenEnergyPlatform/examples/blob/master/api/MaStR-API/BNetzA_MaStR_API.ipynb)
> 
> Link to Marktstammdatenregister: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStR)
> Link to Documentation: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStRHilfe/index.html)
> Link to API Documentation: [www.marktstammdatenregister.de](https://www.marktstammdatenregister.de/MaStRHilfe/subpages/webdienst.html)
> WSDL: [.../MaStRAPI/wsdl/mastr.wsdl](https://www.marktstammdatenregister.de/MaStRAPI/wsdl/mastr.wsdl)
> Data license: [https://www.govdata.de/dl-de/by-2-0](https://www.marktstammdatenregister.de/MaStR/Startseite/Impressum)
> **Data Download**: [reiner-lemoine-institut.de](https://reiner-lemoine-institut.de/datenveroeffentlichung-aus-dem-marktstammdatenregister-der-bundesnetzagentur/)
> 
> **status** (number of units / number of units with geolocation)
> 
> version	date	unit	wind	hydro	biomass	solar
> v1.1	2019-03-01	1862005	30566 / 12099	7453 / 1725	18337 / 11366	804365 / 52147 (x1)
> v1.2	2019-03-03	1884005	31312 / 13166	7671 / 1845	22873 / 15656	1799323 / 103423 (x1)
> v1.3	2019-04-12	1965200	32920 / 14337	8160 / 2166	25369 / 17888	1861631 / 98152 (x1)
> v1.4	2019-06-11	2110197	35540 / 16413	8602 / 2472	26991 / 19214	tba / tba
> v1.5	tba	tba	tba / tba	tba / tba	tba / tba	tba / tba
> (x1) not included in the release

The Link to the API tutorial seems to be dead. I would really like to see how to acces the MASTR with python. I did not manage to do this on my own, unfortunately. So, help is appreciated.
