### ISSUE TITLE
Make code SQLA 2.0 compatible

### ISSUE THREAD

**Issue by deniztepe** [OpenEnergyPlatform/open-MaStR#403]
The SQLAlchemy version 2 is available as beta version on pypi. There might be some compatibility issues once the new version is stable. 

- [x] Upgrade to SQLA v2 and check the source code
- [x] Test the edits afterwards with a lower version

Came up in #395/#399

**Comment by nesnoj** [comment]
Some notes for further work:
- current implementation is not compatible with SQLA >= 2.0, e.g. as implicit and "connectionless" execution [have been removed](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed)
- first steps have been done in #399
- manually test all functions which use DB i/o - even bettr: all steps are included in unit tests
- (remove version pinning, cf. #404)

**Comment by deniztepe** [comment]
I will continue with the implementation on branch feature-403 based on commit 8ed8733e299855c3c8c0a5d75ba6e53fca499436 . The fix would make it to the next release before a version pinning is necessary. I will run today a complete download and then push my changes.

**Comment by deniztepe** [comment]
Closed with #405
