### ISSUE TITLE
Prevent install of SQLA>=2.0

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#404]
Until #403 is solved, the install of SQLAlchemy>=2 should be avoided. This is important right now since there's some strange behaviour:
1. Install via pypi (**virtualenv**): installs `SQLAlchemy==1.4.45` :heavy_check_mark: 
2. Manual install via `pip -e path/to/cloned/repo/` (**virtualenv**): installs `SQLAlchemy==1.4.45` :heavy_check_mark:
3. Manual install via `python setup.py install` (**virtualenv** and **conda**): installs `SQLAlchemy==2.0.0b4` :no_entry:
  -> reason for #395 

2.+3. should have the same result, but something goes wrong using the 3rd way. Same with conda - the standard way described in the readme. Only pinning to `sqlalchemy<2.0` works out.

I think it does no harm if we pin it to <2 until #403 is completed. What do you think, @deniztepe?

**Comment by nesnoj** [comment]
Alternatively, the installation via `pip install -e ...` could replace the current instructions but that's not really failsafe..

**Comment by deniztepe** [comment]
Closed with #405
