### ISSUE TITLE
Try bump2version for automatic version increment

### ISSUE THREAD

**Issue by deniztepe** [OpenEnergyPlatform/open-MaStR#406]
The command line program [bump2version](https://pypi.python.org/pypi/bump2version) enables incrementing the version number throughout entire repository with one command. This would shorten few steps in release procedure, including test versioning for test-pypi #382 as well.

**Comment by deniztepe** [comment]
Pending until next release

**Comment by FlorianK13** [comment]
We used bump2version in the release of v0.13.0 and it worked.
