### ISSUE TITLE
No values in `storages.NutzbareSpeicherkapazitaet`

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#416]
The attribute `NutzbareSpeicherkapazitaet` in the storage table is always nan.
However, it is filled on the website ([example](https://www.marktstammdatenregister.de/MaStR/Einheit/Detail/IndexOeffentlich/5649386#speicher)) and given in the `AnlagenStromSpeicher_*.xml` files.

Do you observe the same in your exported datasets?

**Comment by FlorianK13** [comment]
The download speed today is so bad, I havent manage to get the current xml files to test it.

**Comment by FlorianK13** [comment]
Strangely, for storages there are three tables (all other technologies have two tables):
AnlagenEEGSpeicher - storage_eeg
AnlagenStromSpeicher - storage_units
EinheitenStromSpeicher - storage_extended

@nesnoj In storage_units you can find the values for `NutzbareSpeicherkapazitaet`.

**Comment by nesnoj** [comment]
> Strangely, for storages there are three tables (all other technologies have two tables): AnlagenEEGSpeicher - storage_eeg AnlagenStromSpeicher - storage_units EinheitenStromSpeicher - storage_extended
> 
> @nesnoj In storage_units you can find the values for `NutzbareSpeicherkapazitaet`.

I see, thank you. While the join of `storage_extended` and `storage_units` could be made part of the database creation, it's probably too specific raising the question why we don't do this for other data, e.g. grid information. I've put it on the postprocessing list #411.
