### ISSUE TITLE
docker-compose.yml does not exist in package

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#418]
When you install the package using `pip install open-mastr` the docker-compose.yml file is not part of the package. Hence, `engine='docker-postgres'` does not work.

**Comment by FlorianK13** [comment]
Maybe we should delete the possibility to use docker compose? It would make the package easier to handle. And if someone wants to use docker, they can create a database there and specifiy the engine in the `Mastr(engine=engine)` parameter.

What do you think @Ludee @chrwm

**Comment by FlorianK13** [comment]
The `entrypoints` folder in the main directory is also unused if the docker feature is removed. (Probably it is also unused even if we do not remove the docker feature)

**Comment by chrwm** [comment]
Put docker-compose.yaml in scripts & delete docker stuff in code and add paragraph on how-to-use in docs.
