### ISSUE TITLE
Release version v0.13.0 - Fixes

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#425]
A few bugfixes as patch release:

- [x] Add versions to `changelog.md`
- [x] Fix and update package metadata in `setup.py`
- [x] Update `citation.cff`
- [x] Release on github

**Comment by FlorianK13** [comment]
I tested the release v0.13.0 branch and everything worked fine.

**Comment by chrwm** [comment]
Same here, let the main.py run successfully.

**Comment by FlorianK13** [comment]
Release branch was merged in #429
