### ISSUE TITLE
Bulk import: parsing error after table 'AnlagenEegSpeicher_4.xml'

### ISSUE THREAD

**Issue by alexander-roth** [OpenEnergyPlatform/open-MaStR#431]
Hi, I stumbled over a bug when running the bulk import. 

I ran the following code (Windows 10, Python 3.9):

```
from open_mastr import Mastr
db = Mastr()
db.download(method='bulk', bulk_cleansing = True)
```
However, the parsing process always breaks after table 'AnlagenEegSpeicher_4.xml'.
![image](https://user-images.githubusercontent.com/57187600/219363908-f4816202-376f-4adb-be97-512b69616d84.png)

The import of specific tables only seems to work, yet something is off in the table 'storage' which cannot be imported alone as the same error pops up. Is that a bug of am I doing something wrong?

**Comment by chrwm** [comment]
Hi @alexander-roth please run `pip install --upgrade open-mastr`.

We just released a new version. Please try and report if the bug isn't fixed.

**Comment by FlorianK13** [comment]
I ran it with open-master 0.13.0 and the error did not come up. However the MaStR from BNetzA changes every day, so if you still have the same error when using v0.13.0 you could also state the date of the underlying xml download you are using.

**Comment by alexander-roth** [comment]
> Hi @alexander-roth please run `pip install --upgrade open-mastr`.
> 
> We just released a new version. Please try and report if the bug isn't fixed.

Hi @chrwm, thanks for your super-fast answer. Now everything seems to work. I'll close it for now, thanks again for the swift help!

**Comment by chrwm** [comment]
Glad to see it working!
