### ISSUE TITLE
Make the download work, if you are using a proxy (globally)

### ISSUE THREAD

**Issue by JochB** [OpenEnergyPlatform/open-MaStR#433]
We do use a proxy server for the communication with the "outer world". 
Thus, the communication with the code example given in the documentation ends up with a communication error.
In order not to set a proxy for each communication step within the code, I implemented the following code from https://stackoverflow.com/questions/31639742/how-to-pass-all-pythons-traffics-through-a-http-proxy:  

`import os
proxy = 'http://<user>:<pass>@<proxy>:<port>'
os.environ['http_proxy'] = proxy 
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy`

Maybe you could update the documentation with these lines to ease the work for anyone facing the same issue.

**Comment by FlorianK13** [comment]
Hi @JochB and thanks for your comment. We will discuss this issue and let you know if and how we will add it to the documentation.
