### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#434]
## Deadline: 15.10.2023
Our documentation page is not really up to date. I heard from some people that they have problems using the open-mastr based on the documentation page.

- [x] Create mkdocs infrastructure files @FlorianK13 
- [x] Create root structure @FlorianK13 
- [x] Update docstrings @FlorianK13 
- [x] The dataset - Soap API @chrwm 
- [x] The dataset - CSV @chrwm 
- [x] Add mike versioning
~- [ ] Check if mike versioning works on readthedocs @chrwm~
- [x] Put all advanced pages in a `advanced.md` file @FlorianK13 
- [x] Document bulk functionalities in Advanced or References (High level mermaid diagram mastr website to sqlite to csv) @FlorianK13 
- [x] index.md: Merge table 'Contributions of open-mastr' with existing bullet points @chrwm 
- [x] Document the MaStRAPI bindings explicitly, maybe in getting started @chrwm 
- [x] Screenshot from DBBrowser at getting started @FlorianK13 
- [x] `datasets.md` put description of tables in an tabs element @FlorianK13 
- [x] `datasets.md` put original data model screenshot and translated on in tabs element @FlorianK13 
- [x] `advanced/config.md` see if the project directory descrpition is up to date and add descriptions for missing files / folders @chrwm 
- [x] Delete all unused `.rst` files when the work is finished @FlorianK13 @chrwm 

## Ideas of solution

We have outdated chapters that can be deleted - they still can be accessed if the documentation of earlier versions is still hosted in readthedocs. 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by chrwm** [comment]
In my opinion we should update the sphinx theme, RTD is not very pretty.
https://sphinx-themes.org/

We should consider to move from sphinx to mkdocs due to the simplicity of editing markdown compared to rst.
https://squidfunk.github.io/mkdocs-material/

**Comment by FlorianK13** [comment]
When migrating the documentation from .rst to .mk this would also give the opportunity to sort out old stuff.

**Comment by FlorianK13** [comment]
We could have the following structure. I marked `chapters` with bounding boxes and descriped a bit of the content. Some of the names could be chosen better, so we have to discuss this further. What do you think @chrwm ?

Main Content:
* `Getting started`
  * `Downloading the MaStR data`
  * `Accessing the database`
  * `Exporting data to csv`
* `The dataset`: Structure of newly created folders
  * `Database`: How to change to postgres etc, which tables you get, what data they contain
  * `CSV`: Which files you get, what they contain, how they are created
  * `The two data sources`
    * `xml Download`
    * `Soap API`: Getting API credentials
* `Development`: Also adding new tools we use: pre-commit hooks, the different github actions, the guide to publish the python package, etc.
* `API-Reference`


Few more thoughts:
* Instead of documenting the data and the API functions, we should refer to the documentation at marktstammdatenregister.de By doing so, we don't need to update our documentation every time the data changes.

**Comment by FlorianK13** [comment]
@chrwm and me think about converting the documentation to `mkdocs` and hence use `.md` files for the documentation. 

@Ludee I remember that you intentionally switched to `.rst` files, especially for the `Readme.rst`. Can you shortly name the reasons for doing so?

**Comment by Ludee** [comment]
> @Ludee I remember that you intentionally switched to .rst files, especially for the Readme.rst. Can you shortly name the reasons for doing so?

I only changed the README.rst, this will not be part of the new MkDocs page.

**Comment by FlorianK13** [comment]
@r0gga @chrwm Thanks for adding the open-mastr icon. Is there also another color possible for the favicon? In white it is hardly visible in the browser tab.
