### ISSUE TITLE
Provide zipped sqlite database

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#447]
The final sqlite database `open-mastr.db` has about 1.5 GB in compressed format. Would it be an idea to regularly upload this database to zenodo (or somewhere else)?

**Comment by chrwm** [comment]
I guess this would be an offer to people who can write sql to handle/export tables but lack expertise in unwrapping XML?

What is the added benefit compared to operating open-mastr and having the option to getting the `open-mastr.db` daily?

**Comment by FlorianK13** [comment]
I see two advantages: You would have the full database within few minutes (instead of one hour) and you could get it independant of current bugs in the python package.

**Comment by nesnoj** [comment]
I like the idea but I think the current CSV way might be easier for many users (and XML - especially the process of combining all those files - is definitely a barrier).

As first step, the [CSVs on zenodo](https://zenodo.org/record/7387843) could be updated regularly (e.g. adding a step to the manual release procedure). Also, there's a github hook to zenodo which can be used to trigger publication (if running the tool on GH actions is possible though..)

**Comment by FlorianK13** [comment]
@nesnoj Using the GH actions is probably not possible as the building of the dataset takes ~ 1 hour. We could however think about solutions where we use our own server and something like airflow to trigger regular building, verification/analysis, and uploading of the data. Maybe we have some time in future research projects for such topics.

**Comment by chrwm** [comment]
At RLI open-mastr runs on a dedicated server and could be triggered with a cronjob on regular basis. This setup already ran in the past.
