### ISSUE TITLE
Automated OEP upload

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#45]
The upload of the raw data into the OEP is not implemented yet.
The basics are already there: https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/sessions.py#L75-L103

**Comment by FlorianK13** [comment]
I'd assume that this is no feature that should be in the python package - not everyone using the package should be able to upload their data to OEP? Otherwise this could happen by mistake? 

I would close the issue, you can reopen if you disagree :)
