### ISSUE TITLE
Value mapping for `ArtDerFlaecheIds` is not implemented

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#463]
The ids given in `solar_extended.ArtDerFlaecheIds` are not replaced with the ones from the Katalogwerte (Konversionsfläche, Ackerland, ... cf. [docs](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/Funktionen_MaStR_Webdienste_V1.2.39.html#solarflaechenartenum)).
I use the latest stable from PyPI (0.13.2)

I tag this as a bug but if this a feature to you, please retag ;)

**Comment by FlorianK13** [comment]
Thanks for the issue, I'll try to reproduce the bug.

**Comment by FlorianK13** [comment]
This is fixed in #464

**Comment by nesnoj** [comment]
Thank you!
