### ISSUE TITLE
A release on master needs to be made

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/open-MaStR#48]
This is different from the release of the data. For the release on master I would like to have working code and commented functions. I would require that we don't code any further feature before the state of master is clean again :)

**Comment by Bachibouzouk** [comment]
@Ludee what do you think?

**Comment by ghost** [comment]
Please inform me where you want further commenting on #44 @Bachibouzouk

**Comment by Bachibouzouk** [comment]
"Every function should have a doctring and every docstring should not be empty" is the rule to iterate over all functions from the modules you modified @solar-c :)

**Comment by Ludee** [comment]
> I would require that we don't code any further feature before the state of master is clean again :)

THIS!

**Comment by ghost** [comment]
rechecked all files I worked on. I think I found all stuff I worked on which didn't have a complete docsting yet.

**Comment by Bachibouzouk** [comment]
> rechecked all files I worked on. I think I found all stuff I worked on which didn't have a complete docsting yet.

Great, thank you :)

**Comment by Bachibouzouk** [comment]
@Ludee, I would suggest we merge Release/v0.9.0 (#52) into master and follow directly with a Release/v0.9.1 so that we can clearly see the few fixes we make to address the remaining issues.

**Comment by Ludee** [comment]
Without @Bachibouzouk as git-master I will collect all features in dev branch until I get a clean data version.

**Comment by chrwm** [comment]
v0.9.0 has been released. Thus, the issue is outdated.
