### ISSUE TITLE
Identify as open-mastr package when requesting data from marktstammdatenregister.de

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#489]
We could add a small identification in the request header to identify as python package user when the data is requested from BNetzA.

**Comment by maurerle** [comment]
This should be done setting by setting a `User-Agent` like `open-mastr/x.x requests/y.y python/z.z` in the requests call and similar to the header in:
https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/open_mastr/xml_download/utils_download_bulk.py#L125

**Comment by FlorianK13** [comment]
@maurerle I also think this is the right approach. Due to limited resources this was not done yet. If you wish to contribute we are always happy about Pull Requests :)

**Comment by maurerle** [comment]
Don't know what went wrong, as the merged PR #526 stated
`closes #489` - but it did not close this issue when merged :shrug: 

Can you close it @FlorianK13 ?
