### ISSUE TITLE
Fix pytests

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#497]
## Description of the issue

Describe the problem in as much detail as possible.
Focus on the expected and current behavior. 
If necessary, create a screenshot and insert below.

## Steps to Reproduce
1.
2.
3.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by FlorianK13** [comment]
- [ ] Update github action versions

**Comment by FlorianK13** [comment]
The failed tests do only come from the mirror class, which might be deprecated soon - hence I'm missing the motivation to dig even deeper into the cause of this problem. To me it seems like our tests will either fail from now on or we delete the mirror tests, or @chrwm finds the time to repair these tests.
