### ISSUE TITLE
`NetzbetreiberpruefungStatus` now has values 0,1, and 2

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#498]
Until now we only hat 0 for `no inspection` and 1 for `DSO inspected`. We need to check what 2 means and why it is not replaced by a string value.

**Comment by FlorianK13** [comment]
From the Changelog of the new Data Release I have this line:
Webportal und Webdienst: Neuer Netzbetreiberprüfungsstatus "Nicht vorgesehen" bei steckerfertigen Solaranlagen (SSA)
So I assume this is the third category

**Comment by FlorianK13** [comment]
I contacted BNetzA and I hope that they include the values in the table `katalogwerte` soon.

**Comment by nesnoj** [comment]
I checked today's bulk data and they haven't been included in `katalogwerte` yet.. :(

**Comment by nesnoj** [comment]
@FlorianK13 

The values changed back again to 2954, 2955, ... and not replaced although they are included in the Katalogwerte.

![image](https://github.com/user-attachments/assets/ddd53169-4df0-4202-b3c9-a1de66ceea9e)

I move this to a new issue
