### ISSUE TITLE
MaStR features

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#5]
The current scripts still need some improvements. Feel free to pick one and implement. Since it's a "stable" version for wind, hydro, biomass and pv, please use feature branches and PR. Hotfixes can be pushed to Master. OpenEnergyPlatform/open-MaStR#4 

- [x] Include Kernenergie #74
- [ ] Include Consumer #34, #163 
- [x] Include GeoSolarthermieGrubenKlaerschlamm #37
- [x] Include Verbrennung #38
- [x] Include KWK #39
- [x] Include Storages #24
- [ ] Include Market Players #100
- [ ] Include Gas #163 
- [x] Implement timeout and reconnect for 23:59~0:45
- [x] Implement parallel download (optimise download for solar)
- [x] Implement automatic continuation for restart
- [x] Improve "bare except"

**Comment by Bachibouzouk** [comment]
@Ludee , @solar-c If items get ticked, please link it to the PR or commit number (by editing the issue description)!

**Comment by Ludee** [comment]
This is the workload for the next releases.

**Comment by chrwm** [comment]
Discussion is continued in

-  #100 for Marktakteure,
-  #163 for gas and consumers.
