### ISSUE TITLE
Is it possible to get information if storages are co-located with a solar or wind plant?

### ISSUE THREAD

**Issue by tomfelder94** [OpenEnergyPlatform/open-MaStR#518]
As mentioned in the title I would like to know if it is possible to figure out which storages (typically batteries) are co-located with productions plants (ideally a mapping between them). I was not able to figure out if such a mapping exists in the MaStR data.

Any help is appreciated, thank you!

**Comment by nesnoj** [comment]
Hey @tomfelder94! Actually, this is rather a mastr question and not tool-related. But in a nutshell:

The tables are linked via the location -> attribute `LokationMastrNummer`, so you can join e.g. the tables `solar_extended` and `storage_extended` on this attribute. (More info on the location are provided in the table `locations_extended`.)

This is documented in the [mastr object schema](https://www.marktstammdatenregister.de/MaStRHilfe/files/webdienst/Objektmodell%20-%20Fachliche%20Ansicht%20V1.2.0.pdf) which is also linked in the [open-mastr docs](https://open-mastr.readthedocs.io/en/latest/dataset/#mastr-data-model).

Hope that helps! :)

**Comment by nesnoj** [comment]
@tomfelder94 Please close this issue if solved - thx!
