### ISSUE TITLE
Custom path for home directory

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#520]
It seems like the path `~/.open-mastr` is not configureable. Or do you know of a way to change the home path of the downloaded files @chrwm ? We could extend the funtion [def get_project_home_dir():](https://github.com/OpenEnergyPlatform/open-MaStR/blob/f18ecac04e83fded3b19f8fe891e545a6d2ed645/open_mastr/utils/config.py#L35C1-L35C28) to read an evironment variable? Or the `Mastr.init()` function gets a project home path variable?

**Comment by chrwm** [comment]
I implemented functions already in this [PR](https://github.com/OpenEnergyPlatform/open-MaStR/pull/402/files).

It reads already the variable "OUTPUT_PATH", which your can set in your environment variables or set in the main.py script 
```
os.environ['OUTPUT_PATH'] = "/your/custom/output_path"
```

However, as stated it will just change the path for: csv-export, database, xml-export.
The log file remains in `~/.open-mastr`, from what I remember it would have been more of a hustle to change that.
