### ISSUE TITLE
Mistake in Example Code Snippet in documentation

### ISSUE THREAD

**Issue by cpschau** [OpenEnergyPlatform/open-MaStR#521]
The example for exporting data in the "Getting Started" section appears to contain a small mistake. The first line should likely be tables=["wind", "grids"] instead of tables=["wind", "grid"] (https://open-mastr.readthedocs.io/en/latest/getting_started/#exporting-data).

This issue is part of a https://github.com/openjournals/joss-reviews/issues/6684

**Comment by FlorianK13** [comment]
The fix was merged to develop in #523 and will be part of the next release v0.14.4
