### ISSUE TITLE
Addition of table overview in Getting Started

### ISSUE THREAD

**Issue by cpschau** [OpenEnergyPlatform/open-MaStR#522]
While the documentation provides an extensive explanation of the data model, the "Getting Started" section could be enhanced with an example that lists all available tables in the database e.g. `df = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", con=db.engine)`.

This issue is part of a https://github.com/openjournals/joss-reviews/issues/6684

**Comment by FlorianK13** [comment]
The fix was merged to develop in #523 and will be part of the next release v0.14.4
