### ISSUE TITLE
The issue is that the download of yesterday's xml file does not call gen_url with the new variable now

### ISSUE THREAD

**Issue by wok77** [OpenEnergyPlatform/open-MaStR#533]
First: This is a great project and having MaStR as SQL database is very useful for various analysis questions.

I just wanted to download the latest dataset and as it was a few hours after midnight, I ran into the following problem: The file for today is not yet available, but the mechanism to download the file from yesterday did not work (as it did not generated a new URL).

In line 130 (branch: develop) of utils_download_bulk.py 'now' is calculated for yesterday, but the new URL is not generated using gen_url(now) before starting the download.

Adding the missing call to gen_url solves the problem:

         now = time.localtime(time.mktime(now) - (24 * 60 * 60)) # subtract 1 day from the date
+        url = gen_url(now)
         r = requests.get(url, stream=True)

### PR-Assignee
- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CHANGELOG.md)
- [ ] 📙 Update the documentation

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by wok77** [comment]
@FlorianK13 This is my first contribution and pull request. Not sure how I can assign the PR-Assignee and Review. Can you please support. Thanks!

**Comment by FlorianK13** [comment]
Hi @wok77, thanks for your PR. I'll have a look at it today.

**Comment by FlorianK13** [comment]
This is merged to develop.
