### ISSUE TITLE
Make `CONTRIBUTING.md` less frightening

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#535]
I think our `CONTRIBUTING.md` can scare people, especially new people who have not contributed to Open Source Software before. Maybe we can add a short sentence at the beginning, encouraging people to do as good as they can but that it is not a bad thing if they forget one of the steps there and that we are happy to help.

What do you think @chrwm @nesnoj

**Comment by nesnoj** [comment]
Yes, good point!
I once found this "imposter syndrome disclaimer" which I think is very inviting and a good approach: https://github.com/adriennefriend/imposter-syndrome-disclaimer
There are [multiple projects linked](https://github.com/adriennefriend/imposter-syndrome-disclaimer/blob/master/examples.md) which have very nice modified versions.

What do think?

**Comment by FlorianK13** [comment]
Looks good. This would then replace https://github.com/OpenEnergyPlatform/open-MaStR?tab=readme-ov-file#collaboration I guess? Or even better at the beginning of CONTRIBUTING, similar to [here](https://diffy.readthedocs.io/en/latest/developer/index.html).
