### ISSUE TITLE
Wind download needs improvement

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#54]
The new run fails at EEG downloads.

> 2019-11-30 14:21:47 ERROR Download failed unit_wind_eeg (1459): EEG956686652296
Traceback (most recent call last):
  File "G:\github\OpenEnergyPlatform\open-MaStR\soap_api\mastr_wind_download.py", line 387, in download_unit_wind_eeg
    unit_wind_eeg = get_unit_wind_eeg(unit_wind_list[i])
  File "G:\github\OpenEnergyPlatform\open-MaStR\soap_api\mastr_wind_download.py", line 183, in get_unit_wind_eeg
    c['VerknuepfteEinheit'] =  c['MaStR']['VerknuepfteEinheit']
  File "C:\Anaconda3\envs\py36_mastr\lib\site-packages\zeep\xsd\valueobjects.py", line 124, in __getitem__
    return self.__values__[key]
KeyError: 'MaStR'

Looking at the current release branch, I found some other problems:

- [x] Filter power-unit-wind from power-unit does not remove duplicates
- [x] Filename conventions are not harmonized over all technologies. see [code](https://github.com/OpenEnergyPlatform/open-MaStR/blob/release/v0.9.0/soap_api/utils.py#L27-L50)
- [x] New filenames are not documented in [readme.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/release/v0.9.0/soap_api/readme.md)
- [x] There are two functions with the same name doing similar stuff: [get_power_unit_wind(mastr_unit_wind, mastr_unit_eeg, eeg=False)](https://github.com/OpenEnergyPlatform/open-MaStR/blob/release/v0.9.0/soap_api/mastr_wind_processing.py#L124) and [def get_power_unit_wind(mastr_unit_wind):](https://github.com/OpenEnergyPlatform/open-MaStR/blob/release/v0.9.0/soap_api/mastr_wind_download.py#L40)
- [ ] There are two similar files: mastr_wind_processing.py and mastr_wind_process.py
- [x] Remove override option everywhere. Use version numbers instead!
- [x] Add unique id to each separate download file
- [x] wind permit is missing timestamp and version number
- [x] wind permit index name is missing
- [x] wind permit number is in power-unit and wind-unit, create unique list
- [x] Add function to download failed downloads again before table join
- [x] Add if-else in functions _download to reduce error messages

**Comment by ghost** [comment]
two similar files:
* This is due to the two download workflows we currently have. A decision should be made which one to keep. This decides which file stays. This also leads to the duplicate code:
("there are two functions with the same name doing similar stuff")

Filename conventions / overwrite / ... 
* @Bachibouzouk you spent some time on this, we should document @Ludee s suggestions in readme and hopefully close this topic for good :)

**Comment by Bachibouzouk** [comment]
I wasn't aware that we had two download workflow. What I know is that I didn't touch what was related to wind. For the filename convention I am in favor of what is the most intuitive to @Ludee

**Comment by Bachibouzouk** [comment]
@solar-c you should choose which one of the two files to keep.

**Comment by Ludee** [comment]
I did some major reworks in the release-branch already. Most points are solved.

> For the filename convention I am in favor of what is the most intuitive to @Ludee

I already fixed wind and hydro. I will adapt biomass and hydro later.

**Comment by ghost** [comment]
@Bachibouzouk I am pretty sure you know there are two workflows ;) thats why there were two up-to-date branches we merged into dev. This is something all three of us talked about  a few times. It is not my decision to make.

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk I am pretty sure you know there are two workflows ;) thats why there were two up-to-date branches we merged into dev. This is something all three of us talked about a few times. It is not my decision to make.

I will look at the files then because I don't remember what are the differences

**Comment by Bachibouzouk** [comment]
In the current version of the code, the module `mastr_wind_processing.py` is never used. However it contains a lot of function as opposed to `mastr_wind_process.py`, could we move the parallel download functions to `mastr_wind_download.py` @solar-c (similar as for `mastr_solar_download.py`)?

**Comment by ghost** [comment]
I guess you will first have to decide which workflow should be the one to follow in the next versions. All other actions follow. Either the 'one-click' approach, then a remodeling will take place, or the old approach, then one of the wind files will simply be removed. @Bachibouzouk you should discuss this with @Ludee . 
A better communication about changes and decisions should solve most dicussions including file naming, functions like 'overwrite' and the two workflows.
