### ISSUE TITLE
Fix issue template user_kudos.md

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#544]
## Description of the issue

The workflow to populate USERS.cff doesn't like the double quotes in user_kudos.md
Without them special characters and spaces are processes as expected.

## Ideas of solution

Remove double quotes in user_kudos.md

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by FlorianK13** [comment]
Also the "Many thanks FlorianK13!" should be a "Many thanks @FlorianK13"

**Comment by FlorianK13** [comment]
@chrwm were the problems we saw in the last merge on production fixed by you? So can we merge the new PRs to develop?

**Comment by chrwm** [comment]
Yes the fix is ready for review in https://github.com/OpenEnergyPlatform/open-MaStR/pull/545

**Comment by FlorianK13** [comment]
Ok, I reviewed. You can merge if it is ready.
