### ISSUE TITLE
How to specify the folder path for the SQLite file?

### ISSUE THREAD

**Issue by tomfelder94** [OpenEnergyPlatform/open-MaStR#549]
## Description of the issue

I would like to saved the generated SQLite file at a specific location (a shared SSD drive), not under `$HOME/.open-MaStR/data/sqlite`. Is there a way to provide an absolute path as an argument when initializing the `Mastr` object? Or do I have to manually copy it after each download?

**Comment by nesnoj** [comment]
Hey @tomfelder94!
Yes, this feature was added in v0.14.0 (PR #402). You can change it by adjusting the env variable `OUTPUT_PATH` like
```
os.environ['OUTPUT_PATH'] = "/your/custom/output_path"
```
which is read by [this function](https://github.com/OpenEnergyPlatform/open-MaStR/blob/d17a92c17912f7f96814d309859dc495f942c07a/open_mastr/utils/config.py#L50).

According to #402 this hint was part of the docs but somehow vanished.. :thinking:  - do you know why @FlorianK13 ?

cf. #520

**Comment by FlorianK13** [comment]
Hi @nesnoj I don't know why this is not in the docs. We definitely should add it somewhere because this question comes up regularly.

**Comment by nesnoj** [comment]
> Hi @nesnoj I don't know why this is not in the docs. We definitely should add it somewhere because this question comes up regularly.

Ok, I'll take care..

**Comment by nesnoj** [comment]
Fixed in #550, docs will be updated in next release @tomfelder94
