### ISSUE TITLE
hydro download needs improvements

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#55]
The hydro download has some problems:

- [x] power-units_hydro have many duplicates (due to multiprocess)
- [x] make_hydro needs a rework

**Comment by Bachibouzouk** [comment]
Do you have a number for the downloads with many hydro ? So that one can reproduce the duplicates problem  without having to do too many downloads.

**Comment by Ludee** [comment]
I already fixed this issue ;)
