### ISSUE TITLE
Windkraft in Bayern → Datensatz: 1000 lines with Brutto == Netto (discussion, not Issue)

### ISSUE THREAD

**Issue by denis-bz** [OpenEnergyPlatform/open-MaStR#551]
(not sure if these are issues, please move this to Discussions)

Clicking  Windkraft in Bayern → Datensatz under https://marktstammdatenregister.dev/
gives a .csv with exactly 1000 lines--
```
SEE907461190045,Oberbiberg,,,2023-10-06,472,35,30.0,30.0,Kitekraft Demonstrator bis 30kW Oberbiberg,EEG952304848577
...
SEE978377618305,Hagenbüchach,10.769887,49.524045,2010-04-20,472,35,2000.0,2000.0,Bürgerwindrad      Trübenbronn-Hagenbüchach UG (hb) ＆ Co. KG,EEG995916352513
```
Odd that it's exactly 1000 ? and Brutto is exactly the same as Netto (for these 1000).

What I really want is electricity actually generated per site, per day / month / year / Landkreis.
So MaStR doesn't supply that ? Can you help me find a data provider that does ?
Thanks
cheers
  -- denis

**Comment by FlorianK13** [comment]
Hi @denis-bz, we are actually not the developer of marktstammdatenregister.dev - we just reference to them since it is a nice tool. Their repo and organization are here: https://github.com/marktstammdatenregister-dev

**Comment by FlorianK13** [comment]
And yes, the actual generated electricity is not provided by MaStR. I assume you cannot find this data directly since it belongs to the individual plant owners. For wind and solar you could use weather information to model the generated electricity.

**Comment by denis-bz** [comment]
Hi @FLorianK13,
  thanks for that. So far the people at marktstammdatenregister-dev haven't answered ...
I got their EinheitenWind.xml unpackedwith pandas, no fun,
a few outliers e.g. Longitude < 0  so nobody's used this much ?  Also it's only onshore.

"belongs to the individual plant owners": ok, no surprise,
but most Bundesländer publish GWh actually generated each year --
where does that data come from ?

Model: done that, dwd.de.opendata + tuirbine curves
BUT models with no spot checks against reality ❓

Nice weekend !

**Comment by FlorianK13** [comment]
You can also have a look at the entso data platform where they publish aggregated values of power production: https://transparency.entsoe.eu/

**Comment by denis-bz** [comment]
Thanks @FlorianK13. They seem to make it difficult to export e.g. daily data for 2023 ...

Also, I stumbled across [Links zu Energiestatistik Seiten](https://gist.github.com/dirksan28/46624ea65fc077c14afda9b98aa30377) on gist.github.
