### ISSUE TITLE
NutzbareSpeicherkapazitaet is emplty in storage_extended

### ISSUE THREAD

**Issue by tuxiano** [OpenEnergyPlatform/open-MaStR#560]
## Description of the issue

The column NutzbareSpeicherkapazitaet is empty in storage_extended table. Both in sqlite table csv export

## Steps to Reproduce
I ran the bulk download the 6th of September 2024

## Ideas of solution
I manually joint the the tables storage_extended and storage_units on the column EinheitMastrNummer and VerknuepfteEinheit

## Context and Environment
* Version used: 0.14.4
* Operating system: Windows Server 2019
* Environment setup and (python) version:  python 3.10, dependencies as defined in project.toml

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by nesnoj** [comment]
Hey @tuxiano!

Yes, this column is empty in the original data, cf. #416. But you can find the data in `storage_units` so just join both tables.

**Comment by tuxiano** [comment]
Hi @nesnoj, thank you for the quick response. I can do this manual step, but I would expect that the bnetza_mastr_storage_raw.csv file includes a joint table of storage_extended and storage_units, because they are not exported separately.

**Comment by nesnoj** [comment]
While we explicitly do not alter (e.g. joining) data beyond the core functionality, I see the problem of not offering an export of this table. I'll create a separate issue.

Meanwhile, you can use this for manual export:
`sqlite3 -header -csv -separator "," open-mastr.db "select * from storage_units;" > bnetza_mastr_storage_units_raw.csv`

**Comment by nesnoj** [comment]
As there is a dedicated issue #562 now, I'll close this one. Please reopen if needed.
