### ISSUE TITLE
KeyError: 'geloeschteunddeaktiviertemarktakteure'

### ISSUE THREAD

**Issue by AhmadShelbayeh** [OpenEnergyPlatform/open-MaStR#572]
## Description of the issue
Hi @FlorianK13 
Hey guys, I am getting a key error when downloading the Bulk data.

Code:

from open_mastr import Mastr
db = Mastr()
today_date = datetime.now().strftime('today')
db.download(method='bulk', data=["wind", "market", "permit", "deleted_units"], date=today_date)

KeyError: 'geloeschteunddeaktiviertemarktakteure'

## Context and Environment

Python 3.12.7
open_mastr: Version: 0.14.4

**Comment by FlorianK13** [comment]
Looking at the official [release notes](https://www.marktstammdatenregister.de/MaStRHilfe/subpages/releasenotes.html), there is this newly added table since october 2024:
Gesamtdatenexport: Liste der gelöschten und deaktivierten Marktakteure

**Comment by AhmadShelbayeh** [comment]
Hi @FlorianK13 ,

Thank you for your message. I apologize, but I am not entirely clear on how to resolve the issue at hand. Could you kindly explain what changes I need to make to the following code?

from open_mastr import Mastr
db = Mastr()
today_date = datetime.now().strftime('today')
db.download(method='bulk', data=["wind", "market", "permit", "deleted_units"], date=today_date)

I appreciate your time and support in helping me understand this better.

**Comment by FlorianK13** [comment]
I think this is actually a new bug in our code. The problem is that the dataset changes frequently and we need to update open-mastr everytime when changes occure. I hope we can work on this fast and release a bug fix to version 0.14.5
If it is released, you can download it and the error will vanish.

**Comment by AhmadShelbayeh** [comment]
ok thanks

**Comment by nesnoj** [comment]
@AhmadShelbayeh v0.14.5 has just been released and solves your problem
