### ISSUE TITLE
Reproduce numbers from MaStR Website

### ISSUE THREAD

**Issue by pl52feve** [OpenEnergyPlatform/open-MaStR#573]
## Description of the issue

I was wondering about the differences between the values on the MaStR website and the values I'm getting when bulk downloading. 

## Steps to Reproduce
1. On the https://www.marktstammdatenregister.de/MaStR/Einheit/Einheiten/OeffentlicheEinheitenuebersicht website I used Energieträger = Solarstrahlungsenergie and Betriebs-Status in Betrieb. As of today 16:45 this number is 94428693 kW Bruttoleistung.

2. When I use a fresh bulk download and use the solar_extended table using the same filters as above Energietraeger = 'Solare Strahlungsenergie' and EinheitBetriebsstatus = 'In Betrieb'. Then I'm getting 94489920.913 kW. 

## Ideas of solution

The difference isn't large but I was just wondering if there is a difference to be aware of, because I thought that the numbers should probably be fully  reproducible. So is there anything different in the solar_extended table that makes its final sum larger than the number on the Website? 

## Context and Environment
* Version used: pulled from develop -commit 6bc72541135c8eac66ed6565794e238f5e157957

Thanks a lot for your help!

**Comment by nesnoj** [comment]
Hey @pl52feve, welcome to the repo!
I think it comes from buggy raw data (also originating from old units imported into the register in earlier versions) which are still not fully checked by the DSOs. I guess the data on website is cleaned/filtered/...
I can think of many reasons but it's actually a question for the BNetzA.. ;)

**Comment by pl52feve** [comment]
Hey, thanks for the quick response!
Okay, I just wasn't sure if there was something I overlooked on the repo side. But then I'll reach out to them and see if they can explain (if and if yes) what modifications they make.

**Comment by nesnoj** [comment]
> Hey, thanks for the quick response! Okay, I just wasn't sure if there was something I overlooked on the repo side. But then I'll reach out to them and see if they can explain (if and if yes) what modifications they make.

Sounds good. If you get an answer, I'd be grateful if you could post it here.
