### ISSUE TITLE
Header image is not shown on PyPI

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/open-MaStR#585]
Header is shown in readme but missing on PyPI: https://pypi.org/project/open-mastr/
I guess this is due to the relative path introduced in #493 , sorry for my bad advice.

Alternatively we could obtain it from RTD?
https://open-mastr.readthedocs.io/en/latest/images/README_HeaderThreePartners.svg

**Comment by FlorianK13** [comment]
Using the RTD image in the README could also be problematic, as RTD will build its docs based on the image that is in the README. This could lead to a circular dependency.

**Comment by FlorianK13** [comment]
Probably using this image is the best solution: https://raw.githubusercontent.com/OpenEnergyPlatform/open-MaStR/refs/heads/production/docs/images/README_HeaderThreePartners.svg

**Comment by FlorianK13** [comment]
Additionally I will try to fix the badge for CI, which is always showing `failing`
