### ISSUE TITLE
Solar download needs improvement

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#65]
The parallel download for solar units is not up-to-date.
Improve download logic and documentation.

The parallel solar download is not working correctly.
Implement an automatic pause between 7:00 and 19:00 to ensure stability of the system.

**Comment by Ludee** [comment]
The result of the parallel download seems to be a list (batches) with list with dataframes.
Write all dataframes to files. Please help @solar-c

**Comment by ghost** [comment]
I added a time constraint to wait with the solar process until 17h.
 Is the file saving process fine as is? I get a lot of error output from the new write_to_csv method. I looked into it but wasnt sure if its ok as is now.

**Comment by Ludee** [comment]
Add process status to paralel solar and solar eeg download.
The overall documentation needs major improvements.
