### ISSUE TITLE
Add process status in download_parallel_power_unit

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#73]
Download status is only indicated with a status bar. 
Print badge number in addition to _INFO failed downloads: n_

**Comment by jadeaffenjaeger** [comment]
https://github.com/OpenEnergyPlatform/open-MaStR/pull/99
adds a fancy status bar to all parallel downloads

![Screenshot_20200904_094517](https://user-images.githubusercontent.com/15603149/92213179-63c9e380-ee93-11ea-9e51-4744bf61e4b5.png)

**Comment by gplssm** [comment]
Closed by #99
