### ISSUE TITLE
Check stale branches for reusable code

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/open-MaStR#78]
https://github.com/OpenEnergyPlatform/open-MaStR/branches/all

- [x] [feature/postprocessing](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/postprocessing)
- [x] [feature/postprocessing#101](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/postprocessing%23101)
- [x] [feature/improve_map_plots)](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/improve_map_plots) (manual merge)
- [x] [feature/improve-parallel-download](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/improve-parallel-download) (keep branch until all tests are good!)
- [x] [feature/oep_upload](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/oep_upload) -> no working codebase. hardcopy files
- [x] [feature/retry](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/retry) -> no working codebase. hardcopy files
- [x] [feature/include-gsgk](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/include-gsgk)
- [x] [feature/consumer](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/consumer)
- [x] [feature/storage#98](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature/storage%2398)

**Comment by Ludee** [comment]
I'm merging current developments to dev now.

**Comment by gplssm** [comment]
Closed (at the latest) by #115
