### ISSUE TITLE
Implement unified parallelization interface

### ISSUE THREAD

**Issue by jadeaffenjaeger** [OpenEnergyPlatform/open-MaStR#95]
For easier parallelization, a generic function should be implemented that allows for passing any `get_power_unit_xxx` function as well as a list of candidate IDs as parameter. The function should then execute these function calls in parallel and return a list of the results.

**Comment by jadeaffenjaeger** [comment]
Write access is currently handled by each thread individually without synchronization:
https://github.com/OpenEnergyPlatform/open-MaStR/blob/ae87a9ed49b6b379714fe8d5f266e5634ea6f3fb/soap_api/mastr_solar_download.py#L251

This can lead to file corruption/data loss when multiple threads concurrently access the same file. File access will need to be refactored out of the threaded function.
https://stackoverflow.com/questions/13446445/python-multiprocessing-safely-writing-to-a-file

**Comment by jadeaffenjaeger** [comment]
In order to handle all `get_xxx()` functions, all these functions need to return the same type of value. While for most functions, explicit tracking of failed requests is not required, it unfortunately seems necessary in `get_power_unit()` as a row in the resulting dataframe as it is currently provides no information on the offset in the database that it was retrieved from. As an alternative to changing every other function, I would suggest adding the database index as an additional column in the dataframe. This should make it easier to reconstruct, from a given dataset, which indices still need to be retrieved.

As common convention, I would suggest that all functions that might need to parallelized using the unified interface return a pandas dataframe with the retrieved information upon successful execution and `None` if an error occured. Most functions already implement this behavior.

**Comment by gplssm** [comment]
Closed by #99
