### ISSUE TITLE
Generation of list of elements for download

### ISSUE THREAD

**Issue by jadeaffenjaeger** [OpenEnergyPlatform/open-MaStR#96]
Unit download seems to currently only be based on list indices and does not take into account units which are already downloaded. This seems quite inconvenient when resuming download sessions.
https://github.com/OpenEnergyPlatform/open-MaStR/blob/ae87a9ed49b6b379714fe8d5f266e5634ea6f3fb/soap_api/mastr_wind_download.py#L150

I would suggest improving upon this by generating the list of items to download by simply removing the already downloaded items from the overall list. Consider the following example:
```
a = read_power_unit_solar(fname_power_unit_solar)['EinheitMastrNummer'] # all generators
b = read_unit_solar(fname_solar_unit)['EinheitMastrNummer'] # already downloaded generators
c = a[~a.isin(b)]
```
Series `c` now contains all elements that occur in the global list but were not yet individually downloaded. Is there any reason why the current implementation is preferred? @Ludee

**Comment by Ludee** [comment]
This seems like a nice improvement. It was based on the idea that the download is done in one batch without any problems...
